In [1]:
from skimage.io import imread
import numpy as np
import copy
from matplotlib import pyplot as plt
import cv2 
import os
def load_images(folder):
    images=[]
    for filename in os.listdir(folder):
        img=imread(os.path.join(folder,filename)) ## skimage.io.imread_collection(path)
        if img is not None:
            img=img*255
            img=img.astype('int64')
            images.append(img)
    return(images)

hog_images=load_images("D://Lokin//Data Analytics//TOMTOM//Images//HOG feature descriptor images")

In [8]:
hog_images=np.array(hog_images)

2560

In [15]:
hog_images.shape

(2, 2560, 2560, 3)

In [10]:
from numpy import dtype
from skimage.segmentation import slic
hog_image_seg=np.zeros((hog_images.shape[0],hog_images.shape[1],hog_images.shape[2]))
hog_image_seg=hog_image_seg.astype('float64')

In [11]:
hog_image_seg.shape

(2, 2560, 2560)

In [12]:

from copy import copy 
#hog_image_seg=np.array(hog_image_seg)
num=hog_images.shape[0]
for i in range(0,num):
    print('inspecting image',i)
    print(hog_images[i,:,:,:])
    hog_image_seg[i,:,:]=slic(hog_images[i,:,:,:],n_segments=3000,sigma=5)
    print(hog_image_seg[i,:,:])
    #plt.imshow(hog_image_seg[i,:,:],'gray')
    #plt.show()

inspecting image 0
[[[194 194 160]
  [196 196 162]
  [198 198 164]
  ..., 
  [131 127 118]
  [137 133 124]
  [147 140 132]]

 [[192 192 158]
  [194 194 160]
  [197 197 163]
  ..., 
  [135 131 122]
  [142 138 129]
  [151 144 136]]

 [[189 189 155]
  [192 192 158]
  [195 194 163]
  ..., 
  [141 136 130]
  [147 142 136]
  [156 149 141]]

 ..., 
 [[178 173 153]
  [178 173 153]
  [178 173 153]
  ..., 
  [189 193 156]
  [189 193 156]
  [189 193 156]]

 [[177 172 152]
  [178 173 153]
  [178 173 153]
  ..., 
  [188 192 157]
  [188 192 157]
  [188 192 157]]

 [[177 172 152]
  [178 173 153]
  [178 173 153]
  ..., 
  [188 192 157]
  [188 192 157]
  [187 191 156]]]


C:\Users\Lokin\Anaconda3\lib\site-packages\skimage\util\dtype.py:122: UserWarning: Possible precision loss when converting from int64 to float64
  .format(dtypeobj_in, dtypeobj_out))


[[    0.     0.     0. ...,    53.    53.    53.]
 [    0.     0.     0. ...,    53.    53.    53.]
 [    0.     0.     0. ...,    53.    53.    53.]
 ..., 
 [ 2862.  2862.  2862. ...,  2915.  2915.  2915.]
 [ 2862.  2862.  2862. ...,  2915.  2915.  2915.]
 [ 2862.  2862.  2862. ...,  2915.  2915.  2915.]]
inspecting image 1
[[[167 166 146]
  [167 166 146]
  [169 168 148]
  ..., 
  [168 167 146]
  [166 165 144]
  [162 161 141]]

 [[163 162 142]
  [164 163 143]
  [164 163 143]
  ..., 
  [175 175 151]
  [171 170 149]
  [167 166 145]]

 [[164 163 143]
  [163 162 142]
  [162 161 143]
  ..., 
  [183 183 159]
  [177 177 153]
  [172 171 150]]

 ..., 
 [[198 198 164]
  [200 200 166]
  [199 199 165]
  ..., 
  [143 139 130]
  [149 145 134]
  [155 151 140]]

 [[197 197 163]
  [199 199 165]
  [198 198 164]
  ..., 
  [144 140 131]
  [150 146 135]
  [156 152 141]]

 [[196 196 162]
  [198 198 164]
  [198 198 164]
  ..., 
  [145 141 132]
  [151 147 136]
  [157 153 142]]]
[[    0.     0.     0. ...,   

In [19]:
print(np.unique(hog_images[0,:,:,:]==hog_images[1,:,:,:]))

[False  True]


In [21]:
plt.imshow(hog_images[0,:,:,:])
plt.show()

ValueError: 3-dimensional arrays must be of dtype unsigned byte, unsigned short, float32 or float64

In [12]:
print(np.unique(hog_image_seg[0,:,:]==hog_image_seg[1,:,:]))

[ True]


In [13]:
cent = {}
for k in range(0,num):
    cent[k] = {}
    cent[k]['x']=[]
    cent[k]['y']=[]
    print("image",k)
    print(np.unique(hog_image_seg[k,:,:]))
    for (i,a) in enumerate(np.unique(hog_image_seg[k,:,:])):
        mask=np.zeros(hog_images[k,:,:].shape)
        print("segment",i,"in image",k)
        im=hog_image_seg[k,:,:]
        mask[im==a]=255
#        print(mask)
        seg=np.where(mask==255)
        print(seg[0],seg[1])
        #cent[k]['x'].append(np.mean(seg[0]))
        #cent[k]['y'].append(np.mean(seg[1]))
        print(np.mean(seg[0]), np.mean(seg[1]))
        seg=np.zeros
    #print("centroid for image",k,"segments",x,y)

image 0
[  0.00000000e+00   1.00000000e+00   2.00000000e+00 ...,   2.91300000e+03
   2.91400000e+03   2.91500000e+03]
segment 0 in image 0
[ 0  0  0 ..., 46 46 46] [ 0  0  0 ..., 46 46 46]
23.0 23.0
segment 1 in image 0
[ 0  0  0 ..., 46 46 46] [47 47 47 ..., 93 93 93]
23.0 70.0
segment 2 in image 0
[ 0  0  0 ..., 46 46 46] [ 94  94  94 ..., 140 140 140]
23.0 117.0
segment 3 in image 0
[ 0  0  0 ..., 46 46 46] [141 141 141 ..., 187 187 187]
23.0 164.0
segment 4 in image 0
[ 0  0  0 ..., 46 46 46] [188 188 188 ..., 234 234 234]
23.0 211.0
segment 5 in image 0
[ 0  0  0 ..., 46 46 46] [235 235 235 ..., 281 281 281]
23.0 258.0
segment 6 in image 0
[ 0  0  0 ..., 46 46 46] [282 282 282 ..., 328 328 328]
23.0 305.0
segment 7 in image 0
[ 0  0  0 ..., 46 46 46] [329 329 329 ..., 375 375 375]
23.0 352.0
segment 8 in image 0
[ 0  0  0 ..., 46 46 46] [376 376 376 ..., 422 422 422]
23.0 399.0
segment 9 in image 0
[ 0  0  0 ..., 46 46 46] [423 423 423 ..., 469 469 469]
23.0 446.0
segment 10 in im

[47 47 47 ..., 93 93 93] [1598 1598 1598 ..., 1644 1644 1644]
70.0 1621.0
segment 89 in image 0
[47 47 47 ..., 93 93 93] [1645 1645 1645 ..., 1691 1691 1691]
70.0 1668.0
segment 90 in image 0
[47 47 47 ..., 93 93 93] [1692 1692 1692 ..., 1738 1738 1738]
70.0 1715.0
segment 91 in image 0
[47 47 47 ..., 93 93 93] [1739 1739 1739 ..., 1785 1785 1785]
70.0 1762.0
segment 92 in image 0
[47 47 47 ..., 93 93 93] [1786 1786 1786 ..., 1832 1832 1832]
70.0 1809.0
segment 93 in image 0
[47 47 47 ..., 93 93 93] [1833 1833 1833 ..., 1879 1879 1879]
70.0 1856.0
segment 94 in image 0
[47 47 47 ..., 93 93 93] [1880 1880 1880 ..., 1926 1926 1926]
70.0 1903.0
segment 95 in image 0
[47 47 47 ..., 93 93 93] [1927 1927 1927 ..., 1973 1973 1973]
70.0 1950.0
segment 96 in image 0
[47 47 47 ..., 93 93 93] [1974 1974 1974 ..., 2020 2020 2020]
70.0 1997.0
segment 97 in image 0
[47 47 47 ..., 93 93 93] [2021 2021 2021 ..., 2067 2067 2067]
70.0 2044.0
segment 98 in image 0
[47 47 47 ..., 93 93 93] [2068 2068 2068

[141 141 141 ..., 187 187 187] [423 423 423 ..., 469 469 469]
164.0 446.0
segment 172 in image 0
[141 141 141 ..., 187 187 187] [470 470 470 ..., 516 516 516]
164.0 493.0
segment 173 in image 0
[141 141 141 ..., 187 187 187] [517 517 517 ..., 563 563 563]
164.0 540.0
segment 174 in image 0
[141 141 141 ..., 187 187 187] [564 564 564 ..., 610 610 610]
164.0 587.0
segment 175 in image 0
[141 141 141 ..., 187 187 187] [611 611 611 ..., 657 657 657]
164.0 634.0
segment 176 in image 0
[141 141 141 ..., 187 187 187] [658 658 658 ..., 704 704 704]
164.0 681.0
segment 177 in image 0
[141 141 141 ..., 187 187 187] [705 705 705 ..., 751 751 751]
164.0 728.0
segment 178 in image 0
[141 141 141 ..., 187 187 187] [752 752 752 ..., 798 798 798]
164.0 775.0
segment 179 in image 0
[141 141 141 ..., 187 187 187] [799 799 799 ..., 845 845 845]
164.0 822.0
segment 180 in image 0
[141 141 141 ..., 187 187 187] [846 846 846 ..., 892 892 892]
164.0 869.0
segment 181 in image 0
[141 141 141 ..., 187 187 187]

211.0 1715.0
segment 253 in image 0
[188 188 188 ..., 234 234 234] [1739 1739 1739 ..., 1785 1785 1785]
211.0 1762.0
segment 254 in image 0
[188 188 188 ..., 234 234 234] [1786 1786 1786 ..., 1832 1832 1832]
211.0 1809.0
segment 255 in image 0
[188 188 188 ..., 234 234 234] [1833 1833 1833 ..., 1879 1879 1879]
211.0 1856.0
segment 256 in image 0
[188 188 188 ..., 234 234 234] [1880 1880 1880 ..., 1926 1926 1926]
211.0 1903.0
segment 257 in image 0
[188 188 188 ..., 234 234 234] [1927 1927 1927 ..., 1973 1973 1973]
211.0 1950.0
segment 258 in image 0
[188 188 188 ..., 234 234 234] [1974 1974 1974 ..., 2020 2020 2020]
211.0 1997.0
segment 259 in image 0
[188 188 188 ..., 234 234 234] [2021 2021 2021 ..., 2067 2067 2067]
211.0 2044.0
segment 260 in image 0
[188 188 188 ..., 234 234 234] [2068 2068 2068 ..., 2114 2114 2114]
211.0 2091.0
segment 261 in image 0
[188 188 188 ..., 234 234 234] [2115 2115 2115 ..., 2161 2161 2161]
211.0 2138.0
segment 262 in image 0
[188 188 188 ..., 234 234 23

[282 282 282 ..., 328 328 328] [470 470 470 ..., 516 516 516]
305.0 493.0
segment 335 in image 0
[282 282 282 ..., 328 328 328] [517 517 517 ..., 563 563 563]
305.0 540.0
segment 336 in image 0
[282 282 282 ..., 328 328 328] [564 564 564 ..., 610 610 610]
305.0 587.0
segment 337 in image 0
[282 282 282 ..., 328 328 328] [611 611 611 ..., 657 657 657]
305.0 634.0
segment 338 in image 0
[282 282 282 ..., 328 328 328] [658 658 658 ..., 704 704 704]
305.0 681.0
segment 339 in image 0
[282 282 282 ..., 328 328 328] [705 705 705 ..., 751 751 751]
305.0 728.0
segment 340 in image 0
[282 282 282 ..., 328 328 328] [752 752 752 ..., 798 798 798]
305.0 775.0
segment 341 in image 0
[282 282 282 ..., 328 328 328] [799 799 799 ..., 845 845 845]
305.0 822.0
segment 342 in image 0
[282 282 282 ..., 328 328 328] [846 846 846 ..., 892 892 892]
305.0 869.0
segment 343 in image 0
[282 282 282 ..., 328 328 328] [893 893 893 ..., 939 939 939]
305.0 916.0
segment 344 in image 0
[282 282 282 ..., 328 328 328]

[329 329 329 ..., 375 375 375] [1786 1786 1786 ..., 1832 1832 1832]
352.0 1809.0
segment 417 in image 0
[329 329 329 ..., 375 375 375] [1833 1833 1833 ..., 1879 1879 1879]
352.0 1856.0
segment 418 in image 0
[329 329 329 ..., 375 375 375] [1880 1880 1880 ..., 1926 1926 1926]
352.0 1903.0
segment 419 in image 0
[329 329 329 ..., 375 375 375] [1927 1927 1927 ..., 1973 1973 1973]
352.0 1950.0
segment 420 in image 0
[329 329 329 ..., 375 375 375] [1974 1974 1974 ..., 2020 2020 2020]
352.0 1997.0
segment 421 in image 0
[329 329 329 ..., 375 375 375] [2021 2021 2021 ..., 2067 2067 2067]
352.0 2044.0
segment 422 in image 0
[329 329 329 ..., 375 375 375] [2068 2068 2068 ..., 2114 2114 2114]
352.0 2091.0
segment 423 in image 0
[329 329 329 ..., 375 375 375] [2115 2115 2115 ..., 2161 2161 2161]
352.0 2138.0
segment 424 in image 0
[329 329 329 ..., 375 375 375] [2162 2162 2162 ..., 2208 2208 2208]
352.0 2185.0
segment 425 in image 0
[329 329 329 ..., 375 375 375] [2209 2209 2209 ..., 2255 2255 22

[423 423 423 ..., 469 469 469] [564 564 564 ..., 610 610 610]
446.0 587.0
segment 499 in image 0
[423 423 423 ..., 469 469 469] [611 611 611 ..., 657 657 657]
446.0 634.0
segment 500 in image 0
[423 423 423 ..., 469 469 469] [658 658 658 ..., 704 704 704]
446.0 681.0
segment 501 in image 0
[423 423 423 ..., 469 469 469] [705 705 705 ..., 751 751 751]
446.0 728.0
segment 502 in image 0
[423 423 423 ..., 469 469 469] [752 752 752 ..., 798 798 798]
446.0 775.0
segment 503 in image 0
[423 423 423 ..., 469 469 469] [799 799 799 ..., 845 845 845]
446.0 822.0
segment 504 in image 0
[423 423 423 ..., 469 469 469] [846 846 846 ..., 892 892 892]
446.0 869.0
segment 505 in image 0
[423 423 423 ..., 469 469 469] [893 893 893 ..., 939 939 939]
446.0 916.0
segment 506 in image 0
[423 423 423 ..., 469 469 469] [940 940 940 ..., 986 986 986]
446.0 963.0
segment 507 in image 0
[423 423 423 ..., 469 469 469] [ 987  987  987 ..., 1033 1033 1033]
446.0 1010.0
segment 508 in image 0
[423 423 423 ..., 469 4

[470 470 470 ..., 516 516 516] [1833 1833 1833 ..., 1879 1879 1879]
493.0 1856.0
segment 580 in image 0
[470 470 470 ..., 516 516 516] [1880 1880 1880 ..., 1926 1926 1926]
493.0 1903.0
segment 581 in image 0
[470 470 470 ..., 516 516 516] [1927 1927 1927 ..., 1973 1973 1973]
493.0 1950.0
segment 582 in image 0
[470 470 470 ..., 516 516 516] [1974 1974 1974 ..., 2020 2020 2020]
493.0 1997.0
segment 583 in image 0
[470 470 470 ..., 516 516 516] [2021 2021 2021 ..., 2067 2067 2067]
493.0 2044.0
segment 584 in image 0
[470 470 470 ..., 516 516 516] [2068 2068 2068 ..., 2114 2114 2114]
493.0 2091.0
segment 585 in image 0
[470 470 470 ..., 516 516 516] [2115 2115 2115 ..., 2161 2161 2161]
493.0 2138.0
segment 586 in image 0
[470 470 470 ..., 516 516 516] [2162 2162 2162 ..., 2208 2208 2208]
493.0 2185.0
segment 587 in image 0
[470 470 470 ..., 516 516 516] [2209 2209 2209 ..., 2255 2255 2255]
493.0 2232.0
segment 588 in image 0
[470 470 470 ..., 516 516 516] [2256 2256 2256 ..., 2303 2303 23

[564 564 564 ..., 610 610 610] [611 611 611 ..., 657 657 657]
587.0 634.0
segment 662 in image 0
[564 564 564 ..., 610 610 610] [658 658 658 ..., 704 704 704]
587.0 681.0
segment 663 in image 0
[564 564 564 ..., 610 610 610] [705 705 705 ..., 751 751 751]
587.0 728.0
segment 664 in image 0
[564 564 564 ..., 610 610 610] [752 752 752 ..., 798 798 798]
587.0 775.0
segment 665 in image 0
[564 564 564 ..., 610 610 610] [799 799 799 ..., 845 845 845]
587.0 822.0
segment 666 in image 0
[564 564 564 ..., 610 610 610] [846 846 846 ..., 892 892 892]
587.0 869.0
segment 667 in image 0
[564 564 564 ..., 610 610 610] [893 893 893 ..., 939 939 939]
587.0 916.0
segment 668 in image 0
[564 564 564 ..., 610 610 610] [940 940 940 ..., 986 986 986]
587.0 963.0
segment 669 in image 0
[564 564 564 ..., 610 610 610] [ 987  987  987 ..., 1033 1033 1033]
587.0 1010.0
segment 670 in image 0
[564 564 564 ..., 610 610 610] [1034 1034 1034 ..., 1080 1080 1080]
587.0 1057.0
segment 671 in image 0
[564 564 564 ...

[611 611 611 ..., 657 657 657] [1927 1927 1927 ..., 1973 1973 1973]
634.0 1950.0
segment 744 in image 0
[611 611 611 ..., 657 657 657] [1974 1974 1974 ..., 2020 2020 2020]
634.0 1997.0
segment 745 in image 0
[611 611 611 ..., 657 657 657] [2021 2021 2021 ..., 2067 2067 2067]
634.0 2044.0
segment 746 in image 0
[611 611 611 ..., 657 657 657] [2068 2068 2068 ..., 2114 2114 2114]
634.0 2091.0
segment 747 in image 0
[611 611 611 ..., 657 657 657] [2115 2115 2115 ..., 2161 2161 2161]
634.0 2138.0
segment 748 in image 0
[611 611 611 ..., 657 657 657] [2162 2162 2162 ..., 2208 2208 2208]
634.0 2185.0
segment 749 in image 0
[611 611 611 ..., 657 657 657] [2209 2209 2209 ..., 2255 2255 2255]
634.0 2232.0
segment 750 in image 0
[611 611 611 ..., 657 657 657] [2256 2256 2256 ..., 2303 2303 2303]
634.0 2279.5
segment 751 in image 0
[611 611 611 ..., 657 657 657] [2304 2304 2304 ..., 2351 2351 2351]
634.0 2327.5
segment 752 in image 0
[611 611 611 ..., 657 657 657] [2352 2352 2352 ..., 2401 2401 24

[705 705 705 ..., 751 751 751] [705 705 705 ..., 751 751 751]
728.0 728.0
segment 826 in image 0
[705 705 705 ..., 751 751 751] [752 752 752 ..., 798 798 798]
728.0 775.0
segment 827 in image 0
[705 705 705 ..., 751 751 751] [799 799 799 ..., 845 845 845]
728.0 822.0
segment 828 in image 0
[705 705 705 ..., 751 751 751] [846 846 846 ..., 892 892 892]
728.0 869.0
segment 829 in image 0
[705 705 705 ..., 751 751 751] [893 893 893 ..., 939 939 939]
728.0 916.0
segment 830 in image 0
[705 705 705 ..., 751 751 751] [940 940 940 ..., 986 986 986]
728.0 963.0
segment 831 in image 0
[705 705 705 ..., 751 751 751] [ 987  987  987 ..., 1033 1033 1033]
728.0 1010.0
segment 832 in image 0
[705 705 705 ..., 751 751 751] [1034 1034 1034 ..., 1080 1080 1080]
728.0 1057.0
segment 833 in image 0
[705 705 705 ..., 751 751 751] [1081 1081 1081 ..., 1127 1127 1127]
728.0 1104.0
segment 834 in image 0
[705 705 705 ..., 751 751 751] [1128 1128 1128 ..., 1174 1174 1174]
728.0 1151.0
segment 835 in image 0
[7

[752 752 752 ..., 798 798 798] [1974 1974 1974 ..., 2020 2020 2020]
775.0 1997.0
segment 907 in image 0
[752 752 752 ..., 798 798 798] [2021 2021 2021 ..., 2067 2067 2067]
775.0 2044.0
segment 908 in image 0
[752 752 752 ..., 798 798 798] [2068 2068 2068 ..., 2114 2114 2114]
775.0 2091.0
segment 909 in image 0
[752 752 752 ..., 798 798 798] [2115 2115 2115 ..., 2161 2161 2161]
775.0 2138.0
segment 910 in image 0
[752 752 752 ..., 798 798 798] [2162 2162 2162 ..., 2208 2208 2208]
775.0 2185.0
segment 911 in image 0
[752 752 752 ..., 798 798 798] [2209 2209 2209 ..., 2255 2255 2255]
775.0 2232.0
segment 912 in image 0
[752 752 752 ..., 798 798 798] [2256 2256 2256 ..., 2303 2303 2303]
775.0 2279.5
segment 913 in image 0
[752 752 752 ..., 798 798 798] [2304 2304 2304 ..., 2351 2351 2351]
775.0 2327.5
segment 914 in image 0
[752 752 752 ..., 798 798 798] [2352 2352 2352 ..., 2401 2401 2401]
775.0 2376.5
segment 915 in image 0
[752 752 752 ..., 798 798 798] [2402 2402 2402 ..., 2452 2452 24

[846 846 846 ..., 892 892 892] [799 799 799 ..., 845 845 845]
869.0 822.0
segment 990 in image 0
[846 846 846 ..., 892 892 892] [846 846 846 ..., 892 892 892]
869.0 869.0
segment 991 in image 0
[846 846 846 ..., 892 892 892] [893 893 893 ..., 939 939 939]
869.0 916.0
segment 992 in image 0
[846 846 846 ..., 892 892 892] [940 940 940 ..., 986 986 986]
869.0 963.0
segment 993 in image 0
[846 846 846 ..., 892 892 892] [ 987  987  987 ..., 1033 1033 1033]
869.0 1010.0
segment 994 in image 0
[846 846 846 ..., 892 892 892] [1034 1034 1034 ..., 1080 1080 1080]
869.0 1057.0
segment 995 in image 0
[846 846 846 ..., 892 892 892] [1081 1081 1081 ..., 1127 1127 1127]
869.0 1104.0
segment 996 in image 0
[846 846 846 ..., 892 892 892] [1128 1128 1128 ..., 1174 1174 1174]
869.0 1151.0
segment 997 in image 0
[846 846 846 ..., 892 892 892] [1175 1175 1175 ..., 1221 1221 1221]
869.0 1198.0
segment 998 in image 0
[846 846 846 ..., 892 892 892] [1222 1222 1222 ..., 1268 1268 1268]
869.0 1245.0
segment 999

[893 893 893 ..., 939 939 939] [2068 2068 2068 ..., 2114 2114 2114]
916.0 2091.0
segment 1071 in image 0
[893 893 893 ..., 939 939 939] [2115 2115 2115 ..., 2161 2161 2161]
916.0 2138.0
segment 1072 in image 0
[893 893 893 ..., 939 939 939] [2162 2162 2162 ..., 2208 2208 2208]
916.0 2185.0
segment 1073 in image 0
[893 893 893 ..., 939 939 939] [2209 2209 2209 ..., 2255 2255 2255]
916.0 2232.0
segment 1074 in image 0
[893 893 893 ..., 939 939 939] [2256 2256 2256 ..., 2303 2303 2303]
916.0 2279.5
segment 1075 in image 0
[893 893 893 ..., 939 939 939] [2304 2304 2304 ..., 2351 2351 2351]
916.0 2327.5
segment 1076 in image 0
[893 893 893 ..., 939 939 939] [2352 2352 2352 ..., 2401 2401 2401]
916.0 2376.5
segment 1077 in image 0
[893 893 893 ..., 939 939 939] [2402 2402 2402 ..., 2452 2452 2452]
916.0 2427.0
segment 1078 in image 0
[893 893 893 ..., 939 939 939] [2453 2453 2453 ..., 2505 2505 2505]
916.0 2479.0
segment 1079 in image 0
[893 893 893 ..., 939 939 939] [2506 2506 2506 ..., 255

[ 987  987  987 ..., 1033 1033 1033] [752 752 752 ..., 798 798 798]
1010.0 775.0
segment 1151 in image 0
[ 987  987  987 ..., 1033 1033 1033] [799 799 799 ..., 845 845 845]
1010.0 822.0
segment 1152 in image 0
[ 987  987  987 ..., 1033 1033 1033] [846 846 846 ..., 892 892 892]
1010.0 869.0
segment 1153 in image 0
[ 987  987  987 ..., 1033 1033 1033] [893 893 893 ..., 939 939 939]
1010.0 916.0
segment 1154 in image 0
[ 987  987  987 ..., 1033 1033 1033] [940 940 940 ..., 986 986 986]
1010.0 963.0
segment 1155 in image 0
[ 987  987  987 ..., 1033 1033 1033] [ 987  987  987 ..., 1033 1033 1033]
1010.0 1010.0
segment 1156 in image 0
[ 987  987  987 ..., 1033 1033 1033] [1034 1034 1034 ..., 1080 1080 1080]
1010.0 1057.0
segment 1157 in image 0
[ 987  987  987 ..., 1033 1033 1033] [1081 1081 1081 ..., 1127 1127 1127]
1010.0 1104.0
segment 1158 in image 0
[ 987  987  987 ..., 1033 1033 1033] [1128 1128 1128 ..., 1174 1174 1174]
1010.0 1151.0
segment 1159 in image 0
[ 987  987  987 ..., 1033 1

[1034 1034 1034 ..., 1080 1080 1080] [1739 1739 1739 ..., 1785 1785 1785]
1057.0 1762.0
segment 1226 in image 0
[1034 1034 1034 ..., 1080 1080 1080] [1786 1786 1786 ..., 1832 1832 1832]
1057.0 1809.0
segment 1227 in image 0
[1034 1034 1034 ..., 1080 1080 1080] [1833 1833 1833 ..., 1879 1879 1879]
1057.0 1856.0
segment 1228 in image 0
[1034 1034 1034 ..., 1080 1080 1080] [1880 1880 1880 ..., 1926 1926 1926]
1057.0 1903.0
segment 1229 in image 0
[1034 1034 1034 ..., 1080 1080 1080] [1927 1927 1927 ..., 1973 1973 1973]
1057.0 1950.0
segment 1230 in image 0
[1034 1034 1034 ..., 1080 1080 1080] [1974 1974 1974 ..., 2020 2020 2020]
1057.0 1997.0
segment 1231 in image 0
[1034 1034 1034 ..., 1080 1080 1080] [2021 2021 2021 ..., 2067 2067 2067]
1057.0 2044.0
segment 1232 in image 0
[1034 1034 1034 ..., 1080 1080 1080] [2068 2068 2068 ..., 2114 2114 2114]
1057.0 2091.0
segment 1233 in image 0
[1034 1034 1034 ..., 1080 1080 1080] [2115 2115 2115 ..., 2161 2161 2161]
1057.0 2138.0
segment 1234 in 

[1128 1128 1128 ..., 1174 1174 1174] [235 235 235 ..., 281 281 281]
1151.0 258.0
segment 1302 in image 0
[1128 1128 1128 ..., 1174 1174 1174] [282 282 282 ..., 328 328 328]
1151.0 305.0
segment 1303 in image 0
[1128 1128 1128 ..., 1174 1174 1174] [329 329 329 ..., 375 375 375]
1151.0 352.0
segment 1304 in image 0
[1128 1128 1128 ..., 1174 1174 1174] [376 376 376 ..., 422 422 422]
1151.0 399.0
segment 1305 in image 0
[1128 1128 1128 ..., 1174 1174 1174] [423 423 423 ..., 469 469 469]
1151.0 446.0
segment 1306 in image 0
[1128 1128 1128 ..., 1174 1174 1174] [470 470 470 ..., 516 516 516]
1151.0 493.0
segment 1307 in image 0
[1128 1128 1128 ..., 1174 1174 1174] [517 517 517 ..., 563 563 563]
1151.0 540.0
segment 1308 in image 0
[1128 1128 1128 ..., 1174 1174 1174] [564 564 564 ..., 610 610 610]
1151.0 587.0
segment 1309 in image 0
[1128 1128 1128 ..., 1174 1174 1174] [611 611 611 ..., 657 657 657]
1151.0 634.0
segment 1310 in image 0
[1128 1128 1128 ..., 1174 1174 1174] [658 658 658 ..., 

[1175 1175 1175 ..., 1221 1221 1221] [1316 1316 1316 ..., 1362 1362 1362]
1198.0 1339.0
segment 1379 in image 0
[1175 1175 1175 ..., 1221 1221 1221] [1363 1363 1363 ..., 1409 1409 1409]
1198.0 1386.0
segment 1380 in image 0
[1175 1175 1175 ..., 1221 1221 1221] [1410 1410 1410 ..., 1456 1456 1456]
1198.0 1433.0
segment 1381 in image 0
[1175 1175 1175 ..., 1221 1221 1221] [1457 1457 1457 ..., 1503 1503 1503]
1198.0 1480.0
segment 1382 in image 0
[1175 1175 1175 ..., 1221 1221 1221] [1504 1504 1504 ..., 1550 1550 1550]
1198.0 1527.0
segment 1383 in image 0
[1175 1175 1175 ..., 1221 1221 1221] [1551 1551 1551 ..., 1597 1597 1597]
1198.0 1574.0
segment 1384 in image 0
[1175 1175 1175 ..., 1221 1221 1221] [1598 1598 1598 ..., 1644 1644 1644]
1198.0 1621.0
segment 1385 in image 0
[1175 1175 1175 ..., 1221 1221 1221] [1645 1645 1645 ..., 1691 1691 1691]
1198.0 1668.0
segment 1386 in image 0
[1175 1175 1175 ..., 1221 1221 1221] [1692 1692 1692 ..., 1738 1738 1738]
1198.0 1715.0
segment 1387 in 

[1222 1222 1222 ..., 1268 1268 1268] [2304 2304 2304 ..., 2351 2351 2351]
1245.0 2327.5
segment 1454 in image 0
[1222 1222 1222 ..., 1268 1268 1268] [2352 2352 2352 ..., 2401 2401 2401]
1245.0 2376.5
segment 1455 in image 0
[1222 1222 1222 ..., 1268 1268 1268] [2402 2402 2402 ..., 2452 2452 2452]
1245.0 2427.0
segment 1456 in image 0
[1222 1222 1222 ..., 1268 1268 1268] [2453 2453 2453 ..., 2505 2505 2505]
1245.0 2479.0
segment 1457 in image 0
[1222 1222 1222 ..., 1268 1268 1268] [2506 2506 2506 ..., 2559 2559 2559]
1245.0 2532.5
segment 1458 in image 0
[1269 1269 1269 ..., 1315 1315 1315] [ 0  0  0 ..., 46 46 46]
1292.0 23.0
segment 1459 in image 0
[1269 1269 1269 ..., 1315 1315 1315] [47 47 47 ..., 93 93 93]
1292.0 70.0
segment 1460 in image 0
[1269 1269 1269 ..., 1315 1315 1315] [ 94  94  94 ..., 140 140 140]
1292.0 117.0
segment 1461 in image 0
[1269 1269 1269 ..., 1315 1315 1315] [141 141 141 ..., 187 187 187]
1292.0 164.0
segment 1462 in image 0
[1269 1269 1269 ..., 1315 1315 131

[1316 1316 1316 ..., 1362 1362 1362] [846 846 846 ..., 892 892 892]
1339.0 869.0
segment 1531 in image 0
[1316 1316 1316 ..., 1362 1362 1362] [893 893 893 ..., 939 939 939]
1339.0 916.0
segment 1532 in image 0
[1316 1316 1316 ..., 1362 1362 1362] [940 940 940 ..., 986 986 986]
1339.0 963.0
segment 1533 in image 0
[1316 1316 1316 ..., 1362 1362 1362] [ 987  987  987 ..., 1033 1033 1033]
1339.0 1010.0
segment 1534 in image 0
[1316 1316 1316 ..., 1362 1362 1362] [1034 1034 1034 ..., 1080 1080 1080]
1339.0 1057.0
segment 1535 in image 0
[1316 1316 1316 ..., 1362 1362 1362] [1081 1081 1081 ..., 1127 1127 1127]
1339.0 1104.0
segment 1536 in image 0
[1316 1316 1316 ..., 1362 1362 1362] [1128 1128 1128 ..., 1174 1174 1174]
1339.0 1151.0
segment 1537 in image 0
[1316 1316 1316 ..., 1362 1362 1362] [1175 1175 1175 ..., 1221 1221 1221]
1339.0 1198.0
segment 1538 in image 0
[1316 1316 1316 ..., 1362 1362 1362] [1222 1222 1222 ..., 1268 1268 1268]
1339.0 1245.0
segment 1539 in image 0
[1316 1316 13

[1363 1363 1363 ..., 1409 1409 1409] [1833 1833 1833 ..., 1879 1879 1879]
1386.0 1856.0
segment 1606 in image 0
[1363 1363 1363 ..., 1409 1409 1409] [1880 1880 1880 ..., 1926 1926 1926]
1386.0 1903.0
segment 1607 in image 0
[1363 1363 1363 ..., 1409 1409 1409] [1927 1927 1927 ..., 1973 1973 1973]
1386.0 1950.0
segment 1608 in image 0
[1363 1363 1363 ..., 1409 1409 1409] [1974 1974 1974 ..., 2020 2020 2020]
1386.0 1997.0
segment 1609 in image 0
[1363 1363 1363 ..., 1409 1409 1409] [2021 2021 2021 ..., 2067 2067 2067]
1386.0 2044.0
segment 1610 in image 0
[1363 1363 1363 ..., 1409 1409 1409] [2068 2068 2068 ..., 2114 2114 2114]
1386.0 2091.0
segment 1611 in image 0
[1363 1363 1363 ..., 1409 1409 1409] [2115 2115 2115 ..., 2161 2161 2161]
1386.0 2138.0
segment 1612 in image 0
[1363 1363 1363 ..., 1409 1409 1409] [2162 2162 2162 ..., 2208 2208 2208]
1386.0 2185.0
segment 1613 in image 0
[1363 1363 1363 ..., 1409 1409 1409] [2209 2209 2209 ..., 2255 2255 2255]
1386.0 2232.0
segment 1614 in 

[1457 1457 1457 ..., 1503 1503 1503] [376 376 376 ..., 422 422 422]
1480.0 399.0
segment 1683 in image 0
[1457 1457 1457 ..., 1503 1503 1503] [423 423 423 ..., 469 469 469]
1480.0 446.0
segment 1684 in image 0
[1457 1457 1457 ..., 1503 1503 1503] [470 470 470 ..., 516 516 516]
1480.0 493.0
segment 1685 in image 0
[1457 1457 1457 ..., 1503 1503 1503] [517 517 517 ..., 563 563 563]
1480.0 540.0
segment 1686 in image 0
[1457 1457 1457 ..., 1503 1503 1503] [564 564 564 ..., 610 610 610]
1480.0 587.0
segment 1687 in image 0
[1457 1457 1457 ..., 1503 1503 1503] [611 611 611 ..., 657 657 657]
1480.0 634.0
segment 1688 in image 0
[1457 1457 1457 ..., 1503 1503 1503] [658 658 658 ..., 704 704 704]
1480.0 681.0
segment 1689 in image 0
[1457 1457 1457 ..., 1503 1503 1503] [705 705 705 ..., 751 751 751]
1480.0 728.0
segment 1690 in image 0
[1457 1457 1457 ..., 1503 1503 1503] [752 752 752 ..., 798 798 798]
1480.0 775.0
segment 1691 in image 0
[1457 1457 1457 ..., 1503 1503 1503] [799 799 799 ..., 

[1504 1504 1504 ..., 1550 1550 1550] [1410 1410 1410 ..., 1456 1456 1456]
1527.0 1433.0
segment 1759 in image 0
[1504 1504 1504 ..., 1550 1550 1550] [1457 1457 1457 ..., 1503 1503 1503]
1527.0 1480.0
segment 1760 in image 0
[1504 1504 1504 ..., 1550 1550 1550] [1504 1504 1504 ..., 1550 1550 1550]
1527.0 1527.0
segment 1761 in image 0
[1504 1504 1504 ..., 1550 1550 1550] [1551 1551 1551 ..., 1597 1597 1597]
1527.0 1574.0
segment 1762 in image 0
[1504 1504 1504 ..., 1550 1550 1550] [1598 1598 1598 ..., 1644 1644 1644]
1527.0 1621.0
segment 1763 in image 0
[1504 1504 1504 ..., 1550 1550 1550] [1645 1645 1645 ..., 1691 1691 1691]
1527.0 1668.0
segment 1764 in image 0
[1504 1504 1504 ..., 1550 1550 1550] [1692 1692 1692 ..., 1738 1738 1738]
1527.0 1715.0
segment 1765 in image 0
[1504 1504 1504 ..., 1550 1550 1550] [1739 1739 1739 ..., 1785 1785 1785]
1527.0 1762.0
segment 1766 in image 0
[1504 1504 1504 ..., 1550 1550 1550] [1786 1786 1786 ..., 1832 1832 1832]
1527.0 1809.0
segment 1767 in 

[1551 1551 1551 ..., 1597 1597 1597] [2453 2453 2453 ..., 2505 2505 2505]
1574.0 2479.0
segment 1835 in image 0
[1551 1551 1551 ..., 1597 1597 1597] [2506 2506 2506 ..., 2559 2559 2559]
1574.0 2532.5
segment 1836 in image 0
[1598 1598 1598 ..., 1644 1644 1644] [ 0  0  0 ..., 46 46 46]
1621.0 23.0
segment 1837 in image 0
[1598 1598 1598 ..., 1644 1644 1644] [47 47 47 ..., 93 93 93]
1621.0 70.0
segment 1838 in image 0
[1598 1598 1598 ..., 1644 1644 1644] [ 94  94  94 ..., 140 140 140]
1621.0 117.0
segment 1839 in image 0
[1598 1598 1598 ..., 1644 1644 1644] [141 141 141 ..., 187 187 187]
1621.0 164.0
segment 1840 in image 0
[1598 1598 1598 ..., 1644 1644 1644] [188 188 188 ..., 234 234 234]
1621.0 211.0
segment 1841 in image 0
[1598 1598 1598 ..., 1644 1644 1644] [235 235 235 ..., 281 281 281]
1621.0 258.0
segment 1842 in image 0
[1598 1598 1598 ..., 1644 1644 1644] [282 282 282 ..., 328 328 328]
1621.0 305.0
segment 1843 in image 0
[1598 1598 1598 ..., 1644 1644 1644] [329 329 329 ..., 

[1645 1645 1645 ..., 1691 1691 1691] [ 987  987  987 ..., 1033 1033 1033]
1668.0 1010.0
segment 1912 in image 0
[1645 1645 1645 ..., 1691 1691 1691] [1034 1034 1034 ..., 1080 1080 1080]
1668.0 1057.0
segment 1913 in image 0
[1645 1645 1645 ..., 1691 1691 1691] [1081 1081 1081 ..., 1127 1127 1127]
1668.0 1104.0
segment 1914 in image 0
[1645 1645 1645 ..., 1691 1691 1691] [1128 1128 1128 ..., 1174 1174 1174]
1668.0 1151.0
segment 1915 in image 0
[1645 1645 1645 ..., 1691 1691 1691] [1175 1175 1175 ..., 1221 1221 1221]
1668.0 1198.0
segment 1916 in image 0
[1645 1645 1645 ..., 1691 1691 1691] [1222 1222 1222 ..., 1268 1268 1268]
1668.0 1245.0
segment 1917 in image 0
[1645 1645 1645 ..., 1691 1691 1691] [1269 1269 1269 ..., 1315 1315 1315]
1668.0 1292.0
segment 1918 in image 0
[1645 1645 1645 ..., 1691 1691 1691] [1316 1316 1316 ..., 1362 1362 1362]
1668.0 1339.0
segment 1919 in image 0
[1645 1645 1645 ..., 1691 1691 1691] [1363 1363 1363 ..., 1409 1409 1409]
1668.0 1386.0
segment 1920 in 

[1692 1692 1692 ..., 1738 1738 1738] [1974 1974 1974 ..., 2020 2020 2020]
1715.0 1997.0
segment 1987 in image 0
[1692 1692 1692 ..., 1738 1738 1738] [2021 2021 2021 ..., 2067 2067 2067]
1715.0 2044.0
segment 1988 in image 0
[1692 1692 1692 ..., 1738 1738 1738] [2068 2068 2068 ..., 2114 2114 2114]
1715.0 2091.0
segment 1989 in image 0
[1692 1692 1692 ..., 1738 1738 1738] [2115 2115 2115 ..., 2161 2161 2161]
1715.0 2138.0
segment 1990 in image 0
[1692 1692 1692 ..., 1738 1738 1738] [2162 2162 2162 ..., 2208 2208 2208]
1715.0 2185.0
segment 1991 in image 0
[1692 1692 1692 ..., 1738 1738 1738] [2209 2209 2209 ..., 2255 2255 2255]
1715.0 2232.0
segment 1992 in image 0
[1692 1692 1692 ..., 1738 1738 1738] [2256 2256 2256 ..., 2303 2303 2303]
1715.0 2279.5
segment 1993 in image 0
[1692 1692 1692 ..., 1738 1738 1738] [2304 2304 2304 ..., 2351 2351 2351]
1715.0 2327.5
segment 1994 in image 0
[1692 1692 1692 ..., 1738 1738 1738] [2352 2352 2352 ..., 2401 2401 2401]
1715.0 2376.5
segment 1995 in 

[1786 1786 1786 ..., 1832 1832 1832] [470 470 470 ..., 516 516 516]
1809.0 493.0
segment 2063 in image 0
[1786 1786 1786 ..., 1832 1832 1832] [517 517 517 ..., 563 563 563]
1809.0 540.0
segment 2064 in image 0
[1786 1786 1786 ..., 1832 1832 1832] [564 564 564 ..., 610 610 610]
1809.0 587.0
segment 2065 in image 0
[1786 1786 1786 ..., 1832 1832 1832] [611 611 611 ..., 657 657 657]
1809.0 634.0
segment 2066 in image 0
[1786 1786 1786 ..., 1832 1832 1832] [658 658 658 ..., 704 704 704]
1809.0 681.0
segment 2067 in image 0
[1786 1786 1786 ..., 1832 1832 1832] [705 705 705 ..., 751 751 751]
1809.0 728.0
segment 2068 in image 0
[1786 1786 1786 ..., 1832 1832 1832] [752 752 752 ..., 798 798 798]
1809.0 775.0
segment 2069 in image 0
[1786 1786 1786 ..., 1832 1832 1832] [799 799 799 ..., 845 845 845]
1809.0 822.0
segment 2070 in image 0
[1786 1786 1786 ..., 1832 1832 1832] [846 846 846 ..., 892 892 892]
1809.0 869.0
segment 2071 in image 0
[1786 1786 1786 ..., 1832 1832 1832] [893 893 893 ..., 

[1833 1833 1833 ..., 1879 1879 1879] [1551 1551 1551 ..., 1597 1597 1597]
1856.0 1574.0
segment 2140 in image 0
[1833 1833 1833 ..., 1879 1879 1879] [1598 1598 1598 ..., 1644 1644 1644]
1856.0 1621.0
segment 2141 in image 0
[1833 1833 1833 ..., 1879 1879 1879] [1645 1645 1645 ..., 1691 1691 1691]
1856.0 1668.0
segment 2142 in image 0
[1833 1833 1833 ..., 1879 1879 1879] [1692 1692 1692 ..., 1738 1738 1738]
1856.0 1715.0
segment 2143 in image 0
[1833 1833 1833 ..., 1879 1879 1879] [1739 1739 1739 ..., 1785 1785 1785]
1856.0 1762.0
segment 2144 in image 0
[1833 1833 1833 ..., 1879 1879 1879] [1786 1786 1786 ..., 1832 1832 1832]
1856.0 1809.0
segment 2145 in image 0
[1833 1833 1833 ..., 1879 1879 1879] [1833 1833 1833 ..., 1879 1879 1879]
1856.0 1856.0
segment 2146 in image 0
[1833 1833 1833 ..., 1879 1879 1879] [1880 1880 1880 ..., 1926 1926 1926]
1856.0 1903.0
segment 2147 in image 0
[1833 1833 1833 ..., 1879 1879 1879] [1927 1927 1927 ..., 1973 1973 1973]
1856.0 1950.0
segment 2148 in 

segment 2215 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [47 47 47 ..., 93 93 93]
1950.0 70.0
segment 2216 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [ 94  94  94 ..., 140 140 140]
1950.0 117.0
segment 2217 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [141 141 141 ..., 187 187 187]
1950.0 164.0
segment 2218 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [188 188 188 ..., 234 234 234]
1950.0 211.0
segment 2219 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [235 235 235 ..., 281 281 281]
1950.0 258.0
segment 2220 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [282 282 282 ..., 328 328 328]
1950.0 305.0
segment 2221 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [329 329 329 ..., 375 375 375]
1950.0 352.0
segment 2222 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [376 376 376 ..., 422 422 422]
1950.0 399.0
segment 2223 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [423 423 423 ..., 469 469 469]
1950.0 446.0
segment 2224 in image 0
[1927 1927 1927 ..., 1973 1973 1973] [

[1974 1974 1974 ..., 2020 2020 2020] [1128 1128 1128 ..., 1174 1174 1174]
1997.0 1151.0
segment 2293 in image 0
[1974 1974 1974 ..., 2020 2020 2020] [1175 1175 1175 ..., 1221 1221 1221]
1997.0 1198.0
segment 2294 in image 0
[1974 1974 1974 ..., 2020 2020 2020] [1222 1222 1222 ..., 1268 1268 1268]
1997.0 1245.0
segment 2295 in image 0
[1974 1974 1974 ..., 2020 2020 2020] [1269 1269 1269 ..., 1315 1315 1315]
1997.0 1292.0
segment 2296 in image 0
[1974 1974 1974 ..., 2020 2020 2020] [1316 1316 1316 ..., 1362 1362 1362]
1997.0 1339.0
segment 2297 in image 0
[1974 1974 1974 ..., 2020 2020 2020] [1363 1363 1363 ..., 1409 1409 1409]
1997.0 1386.0
segment 2298 in image 0
[1974 1974 1974 ..., 2020 2020 2020] [1410 1410 1410 ..., 1456 1456 1456]
1997.0 1433.0
segment 2299 in image 0
[1974 1974 1974 ..., 2020 2020 2020] [1457 1457 1457 ..., 1503 1503 1503]
1997.0 1480.0
segment 2300 in image 0
[1974 1974 1974 ..., 2020 2020 2020] [1504 1504 1504 ..., 1550 1550 1550]
1997.0 1527.0
segment 2301 in 

[2021 2021 2021 ..., 2067 2067 2067] [2162 2162 2162 ..., 2208 2208 2208]
2044.0 2185.0
segment 2369 in image 0
[2021 2021 2021 ..., 2067 2067 2067] [2209 2209 2209 ..., 2255 2255 2255]
2044.0 2232.0
segment 2370 in image 0
[2021 2021 2021 ..., 2067 2067 2067] [2256 2256 2256 ..., 2303 2303 2303]
2044.0 2279.5
segment 2371 in image 0
[2021 2021 2021 ..., 2067 2067 2067] [2304 2304 2304 ..., 2351 2351 2351]
2044.0 2327.5
segment 2372 in image 0
[2021 2021 2021 ..., 2067 2067 2067] [2352 2352 2352 ..., 2401 2401 2401]
2044.0 2376.5
segment 2373 in image 0
[2021 2021 2021 ..., 2067 2067 2067] [2402 2402 2402 ..., 2452 2452 2452]
2044.0 2427.0
segment 2374 in image 0
[2021 2021 2021 ..., 2067 2067 2067] [2453 2453 2453 ..., 2505 2505 2505]
2044.0 2479.0
segment 2375 in image 0
[2021 2021 2021 ..., 2067 2067 2067] [2506 2506 2506 ..., 2559 2559 2559]
2044.0 2532.5
segment 2376 in image 0
[2068 2068 2068 ..., 2114 2114 2114] [ 0  0  0 ..., 46 46 46]
2091.0 23.0
segment 2377 in image 0
[2068 

[2115 2115 2115 ..., 2161 2161 2161] [658 658 658 ..., 704 704 704]
2138.0 681.0
segment 2445 in image 0
[2115 2115 2115 ..., 2161 2161 2161] [705 705 705 ..., 751 751 751]
2138.0 728.0
segment 2446 in image 0
[2115 2115 2115 ..., 2161 2161 2161] [752 752 752 ..., 798 798 798]
2138.0 775.0
segment 2447 in image 0
[2115 2115 2115 ..., 2161 2161 2161] [799 799 799 ..., 845 845 845]
2138.0 822.0
segment 2448 in image 0
[2115 2115 2115 ..., 2161 2161 2161] [846 846 846 ..., 892 892 892]
2138.0 869.0
segment 2449 in image 0
[2115 2115 2115 ..., 2161 2161 2161] [893 893 893 ..., 939 939 939]
2138.0 916.0
segment 2450 in image 0
[2115 2115 2115 ..., 2161 2161 2161] [940 940 940 ..., 986 986 986]
2138.0 963.0
segment 2451 in image 0
[2115 2115 2115 ..., 2161 2161 2161] [ 987  987  987 ..., 1033 1033 1033]
2138.0 1010.0
segment 2452 in image 0
[2115 2115 2115 ..., 2161 2161 2161] [1034 1034 1034 ..., 1080 1080 1080]
2138.0 1057.0
segment 2453 in image 0
[2115 2115 2115 ..., 2161 2161 2161] [108

segment 2520 in image 0
[2162 2162 2162 ..., 2208 2208 2208] [1692 1692 1692 ..., 1738 1738 1738]
2185.0 1715.0
segment 2521 in image 0
[2162 2162 2162 ..., 2208 2208 2208] [1739 1739 1739 ..., 1785 1785 1785]
2185.0 1762.0
segment 2522 in image 0
[2162 2162 2162 ..., 2208 2208 2208] [1786 1786 1786 ..., 1832 1832 1832]
2185.0 1809.0
segment 2523 in image 0
[2162 2162 2162 ..., 2208 2208 2208] [1833 1833 1833 ..., 1879 1879 1879]
2185.0 1856.0
segment 2524 in image 0
[2162 2162 2162 ..., 2208 2208 2208] [1880 1880 1880 ..., 1926 1926 1926]
2185.0 1903.0
segment 2525 in image 0
[2162 2162 2162 ..., 2208 2208 2208] [1927 1927 1927 ..., 1973 1973 1973]
2185.0 1950.0
segment 2526 in image 0
[2162 2162 2162 ..., 2208 2208 2208] [1974 1974 1974 ..., 2020 2020 2020]
2185.0 1997.0
segment 2527 in image 0
[2162 2162 2162 ..., 2208 2208 2208] [2021 2021 2021 ..., 2067 2067 2067]
2185.0 2044.0
segment 2528 in image 0
[2162 2162 2162 ..., 2208 2208 2208] [2068 2068 2068 ..., 2114 2114 2114]
2185.0

[2256 2256 2256 ..., 2303 2303 2303] [188 188 188 ..., 234 234 234]
2279.5 211.0
segment 2597 in image 0
[2256 2256 2256 ..., 2303 2303 2303] [235 235 235 ..., 281 281 281]
2279.5 258.0
segment 2598 in image 0
[2256 2256 2256 ..., 2303 2303 2303] [282 282 282 ..., 328 328 328]
2279.5 305.0
segment 2599 in image 0
[2256 2256 2256 ..., 2303 2303 2303] [329 329 329 ..., 375 375 375]
2279.5 352.0
segment 2600 in image 0
[2256 2256 2256 ..., 2303 2303 2303] [376 376 376 ..., 422 422 422]
2279.5 399.0
segment 2601 in image 0
[2256 2256 2256 ..., 2303 2303 2303] [423 423 423 ..., 469 469 469]
2279.5 446.0
segment 2602 in image 0
[2256 2256 2256 ..., 2303 2303 2303] [470 470 470 ..., 516 516 516]
2279.5 493.0
segment 2603 in image 0
[2256 2256 2256 ..., 2303 2303 2303] [517 517 517 ..., 563 563 563]
2279.5 540.0
segment 2604 in image 0
[2256 2256 2256 ..., 2303 2303 2303] [564 564 564 ..., 610 610 610]
2279.5 587.0
segment 2605 in image 0
[2256 2256 2256 ..., 2303 2303 2303] [611 611 611 ..., 

[2304 2304 2304 ..., 2351 2351 2351] [1269 1269 1269 ..., 1315 1315 1315]
2327.5 1292.0
segment 2674 in image 0
[2304 2304 2304 ..., 2351 2351 2351] [1316 1316 1316 ..., 1362 1362 1362]
2327.5 1339.0
segment 2675 in image 0
[2304 2304 2304 ..., 2351 2351 2351] [1363 1363 1363 ..., 1409 1409 1409]
2327.5 1386.0
segment 2676 in image 0
[2304 2304 2304 ..., 2351 2351 2351] [1410 1410 1410 ..., 1456 1456 1456]
2327.5 1433.0
segment 2677 in image 0
[2304 2304 2304 ..., 2351 2351 2351] [1457 1457 1457 ..., 1503 1503 1503]
2327.5 1480.0
segment 2678 in image 0
[2304 2304 2304 ..., 2351 2351 2351] [1504 1504 1504 ..., 1550 1550 1550]
2327.5 1527.0
segment 2679 in image 0
[2304 2304 2304 ..., 2351 2351 2351] [1551 1551 1551 ..., 1597 1597 1597]
2327.5 1574.0
segment 2680 in image 0
[2304 2304 2304 ..., 2351 2351 2351] [1598 1598 1598 ..., 1644 1644 1644]
2327.5 1621.0
segment 2681 in image 0
[2304 2304 2304 ..., 2351 2351 2351] [1645 1645 1645 ..., 1691 1691 1691]
2327.5 1668.0
segment 2682 in 

[2352 2352 2352 ..., 2401 2401 2401] [2304 2304 2304 ..., 2351 2351 2351]
2376.5 2327.5
segment 2750 in image 0
[2352 2352 2352 ..., 2401 2401 2401] [2352 2352 2352 ..., 2401 2401 2401]
2376.5 2376.5
segment 2751 in image 0
[2352 2352 2352 ..., 2401 2401 2401] [2402 2402 2402 ..., 2452 2452 2452]
2376.5 2427.0
segment 2752 in image 0
[2352 2352 2352 ..., 2401 2401 2401] [2453 2453 2453 ..., 2505 2505 2505]
2376.5 2479.0
segment 2753 in image 0
[2352 2352 2352 ..., 2401 2401 2401] [2506 2506 2506 ..., 2559 2559 2559]
2376.5 2532.5
segment 2754 in image 0
[2402 2402 2402 ..., 2452 2452 2452] [ 0  0  0 ..., 46 46 46]
2427.0 23.0
segment 2755 in image 0
[2402 2402 2402 ..., 2452 2452 2452] [47 47 47 ..., 93 93 93]
2427.0 70.0
segment 2756 in image 0
[2402 2402 2402 ..., 2452 2452 2452] [ 94  94  94 ..., 140 140 140]
2427.0 117.0
segment 2757 in image 0
[2402 2402 2402 ..., 2452 2452 2452] [141 141 141 ..., 187 187 187]
2427.0 164.0
segment 2758 in image 0
[2402 2402 2402 ..., 2452 2452 245

[2453 2453 2453 ..., 2505 2505 2505] [799 799 799 ..., 845 845 845]
2479.0 822.0
segment 2826 in image 0
[2453 2453 2453 ..., 2505 2505 2505] [846 846 846 ..., 892 892 892]
2479.0 869.0
segment 2827 in image 0
[2453 2453 2453 ..., 2505 2505 2505] [893 893 893 ..., 939 939 939]
2479.0 916.0
segment 2828 in image 0
[2453 2453 2453 ..., 2505 2505 2505] [940 940 940 ..., 986 986 986]
2479.0 963.0
segment 2829 in image 0
[2453 2453 2453 ..., 2505 2505 2505] [ 987  987  987 ..., 1033 1033 1033]
2479.0 1010.0
segment 2830 in image 0
[2453 2453 2453 ..., 2505 2505 2505] [1034 1034 1034 ..., 1080 1080 1080]
2479.0 1057.0
segment 2831 in image 0
[2453 2453 2453 ..., 2505 2505 2505] [1081 1081 1081 ..., 1127 1127 1127]
2479.0 1104.0
segment 2832 in image 0
[2453 2453 2453 ..., 2505 2505 2505] [1128 1128 1128 ..., 1174 1174 1174]
2479.0 1151.0
segment 2833 in image 0
[2453 2453 2453 ..., 2505 2505 2505] [1175 1175 1175 ..., 1221 1221 1221]
2479.0 1198.0
segment 2834 in image 0
[2453 2453 2453 ...,

[2506 2506 2506 ..., 2559 2559 2559] [1786 1786 1786 ..., 1832 1832 1832]
2532.5 1809.0
segment 2901 in image 0
[2506 2506 2506 ..., 2559 2559 2559] [1833 1833 1833 ..., 1879 1879 1879]
2532.5 1856.0
segment 2902 in image 0
[2506 2506 2506 ..., 2559 2559 2559] [1880 1880 1880 ..., 1926 1926 1926]
2532.5 1903.0
segment 2903 in image 0
[2506 2506 2506 ..., 2559 2559 2559] [1927 1927 1927 ..., 1973 1973 1973]
2532.5 1950.0
segment 2904 in image 0
[2506 2506 2506 ..., 2559 2559 2559] [1974 1974 1974 ..., 2020 2020 2020]
2532.5 1997.0
segment 2905 in image 0
[2506 2506 2506 ..., 2559 2559 2559] [2021 2021 2021 ..., 2067 2067 2067]
2532.5 2044.0
segment 2906 in image 0
[2506 2506 2506 ..., 2559 2559 2559] [2068 2068 2068 ..., 2114 2114 2114]
2532.5 2091.0
segment 2907 in image 0
[2506 2506 2506 ..., 2559 2559 2559] [2115 2115 2115 ..., 2161 2161 2161]
2532.5 2138.0
segment 2908 in image 0
[2506 2506 2506 ..., 2559 2559 2559] [2162 2162 2162 ..., 2208 2208 2208]
2532.5 2185.0
segment 2909 in 

[47 47 47 ..., 93 93 93] [705 705 705 ..., 751 751 751]
70.0 728.0
segment 70 in image 1
[47 47 47 ..., 93 93 93] [752 752 752 ..., 798 798 798]
70.0 775.0
segment 71 in image 1
[47 47 47 ..., 93 93 93] [799 799 799 ..., 845 845 845]
70.0 822.0
segment 72 in image 1
[47 47 47 ..., 93 93 93] [846 846 846 ..., 892 892 892]
70.0 869.0
segment 73 in image 1
[47 47 47 ..., 93 93 93] [893 893 893 ..., 939 939 939]
70.0 916.0
segment 74 in image 1
[47 47 47 ..., 93 93 93] [940 940 940 ..., 986 986 986]
70.0 963.0
segment 75 in image 1
[47 47 47 ..., 93 93 93] [ 987  987  987 ..., 1033 1033 1033]
70.0 1010.0
segment 76 in image 1
[47 47 47 ..., 93 93 93] [1034 1034 1034 ..., 1080 1080 1080]
70.0 1057.0
segment 77 in image 1
[47 47 47 ..., 93 93 93] [1081 1081 1081 ..., 1127 1127 1127]
70.0 1104.0
segment 78 in image 1
[47 47 47 ..., 93 93 93] [1128 1128 1128 ..., 1174 1174 1174]
70.0 1151.0
segment 79 in image 1
[47 47 47 ..., 93 93 93] [1175 1175 1175 ..., 1221 1221 1221]
70.0 1198.0
segment 

[ 94  94  94 ..., 140 140 140] [2115 2115 2115 ..., 2161 2161 2161]
117.0 2138.0
segment 154 in image 1
[ 94  94  94 ..., 140 140 140] [2162 2162 2162 ..., 2208 2208 2208]
117.0 2185.0
segment 155 in image 1
[ 94  94  94 ..., 140 140 140] [2209 2209 2209 ..., 2255 2255 2255]
117.0 2232.0
segment 156 in image 1
[ 94  94  94 ..., 140 140 140] [2256 2256 2256 ..., 2303 2303 2303]
117.0 2279.5
segment 157 in image 1
[ 94  94  94 ..., 140 140 140] [2304 2304 2304 ..., 2351 2351 2351]
117.0 2327.5
segment 158 in image 1
[ 94  94  94 ..., 140 140 140] [2352 2352 2352 ..., 2401 2401 2401]
117.0 2376.5
segment 159 in image 1
[ 94  94  94 ..., 140 140 140] [2402 2402 2402 ..., 2452 2452 2452]
117.0 2427.0
segment 160 in image 1
[ 94  94  94 ..., 140 140 140] [2453 2453 2453 ..., 2505 2505 2505]
117.0 2479.0
segment 161 in image 1
[ 94  94  94 ..., 140 140 140] [2506 2506 2506 ..., 2559 2559 2559]
117.0 2532.5
segment 162 in image 1
[141 141 141 ..., 187 187 187] [ 0  0  0 ..., 46 46 46]
164.0 23

[188 188 188 ..., 234 234 234] [893 893 893 ..., 939 939 939]
211.0 916.0
segment 236 in image 1
[188 188 188 ..., 234 234 234] [940 940 940 ..., 986 986 986]
211.0 963.0
segment 237 in image 1
[188 188 188 ..., 234 234 234] [ 987  987  987 ..., 1033 1033 1033]
211.0 1010.0
segment 238 in image 1
[188 188 188 ..., 234 234 234] [1034 1034 1034 ..., 1080 1080 1080]
211.0 1057.0
segment 239 in image 1
[188 188 188 ..., 234 234 234] [1081 1081 1081 ..., 1127 1127 1127]
211.0 1104.0
segment 240 in image 1
[188 188 188 ..., 234 234 234] [1128 1128 1128 ..., 1174 1174 1174]
211.0 1151.0
segment 241 in image 1
[188 188 188 ..., 234 234 234] [1175 1175 1175 ..., 1221 1221 1221]
211.0 1198.0
segment 242 in image 1
[188 188 188 ..., 234 234 234] [1222 1222 1222 ..., 1268 1268 1268]
211.0 1245.0
segment 243 in image 1
[188 188 188 ..., 234 234 234] [1269 1269 1269 ..., 1315 1315 1315]
211.0 1292.0
segment 244 in image 1
[188 188 188 ..., 234 234 234] [1316 1316 1316 ..., 1362 1362 1362]
211.0 1339

[235 235 235 ..., 281 281 281] [2162 2162 2162 ..., 2208 2208 2208]
258.0 2185.0
segment 317 in image 1
[235 235 235 ..., 281 281 281] [2209 2209 2209 ..., 2255 2255 2255]
258.0 2232.0
segment 318 in image 1
[235 235 235 ..., 281 281 281] [2256 2256 2256 ..., 2303 2303 2303]
258.0 2279.5
segment 319 in image 1
[235 235 235 ..., 281 281 281] [2304 2304 2304 ..., 2351 2351 2351]
258.0 2327.5
segment 320 in image 1
[235 235 235 ..., 281 281 281] [2352 2352 2352 ..., 2401 2401 2401]
258.0 2376.5
segment 321 in image 1
[235 235 235 ..., 281 281 281] [2402 2402 2402 ..., 2452 2452 2452]
258.0 2427.0
segment 322 in image 1
[235 235 235 ..., 281 281 281] [2453 2453 2453 ..., 2505 2505 2505]
258.0 2479.0
segment 323 in image 1
[235 235 235 ..., 281 281 281] [2506 2506 2506 ..., 2559 2559 2559]
258.0 2532.5
segment 324 in image 1
[282 282 282 ..., 328 328 328] [ 0  0  0 ..., 46 46 46]
305.0 23.0
segment 325 in image 1
[282 282 282 ..., 328 328 328] [47 47 47 ..., 93 93 93]
305.0 70.0
segment 326

[329 329 329 ..., 375 375 375] [940 940 940 ..., 986 986 986]
352.0 963.0
segment 399 in image 1
[329 329 329 ..., 375 375 375] [ 987  987  987 ..., 1033 1033 1033]
352.0 1010.0
segment 400 in image 1
[329 329 329 ..., 375 375 375] [1034 1034 1034 ..., 1080 1080 1080]
352.0 1057.0
segment 401 in image 1
[329 329 329 ..., 375 375 375] [1081 1081 1081 ..., 1127 1127 1127]
352.0 1104.0
segment 402 in image 1
[329 329 329 ..., 375 375 375] [1128 1128 1128 ..., 1174 1174 1174]
352.0 1151.0
segment 403 in image 1
[329 329 329 ..., 375 375 375] [1175 1175 1175 ..., 1221 1221 1221]
352.0 1198.0
segment 404 in image 1
[329 329 329 ..., 375 375 375] [1222 1222 1222 ..., 1268 1268 1268]
352.0 1245.0
segment 405 in image 1
[329 329 329 ..., 375 375 375] [1269 1269 1269 ..., 1315 1315 1315]
352.0 1292.0
segment 406 in image 1
[329 329 329 ..., 375 375 375] [1316 1316 1316 ..., 1362 1362 1362]
352.0 1339.0
segment 407 in image 1
[329 329 329 ..., 375 375 375] [1363 1363 1363 ..., 1409 1409 1409]
352

[376 376 376 ..., 422 422 422] [2209 2209 2209 ..., 2255 2255 2255]
399.0 2232.0
segment 480 in image 1
[376 376 376 ..., 422 422 422] [2256 2256 2256 ..., 2303 2303 2303]
399.0 2279.5
segment 481 in image 1
[376 376 376 ..., 422 422 422] [2304 2304 2304 ..., 2351 2351 2351]
399.0 2327.5
segment 482 in image 1
[376 376 376 ..., 422 422 422] [2352 2352 2352 ..., 2401 2401 2401]
399.0 2376.5
segment 483 in image 1
[376 376 376 ..., 422 422 422] [2402 2402 2402 ..., 2452 2452 2452]
399.0 2427.0
segment 484 in image 1
[376 376 376 ..., 422 422 422] [2453 2453 2453 ..., 2505 2505 2505]
399.0 2479.0
segment 485 in image 1
[376 376 376 ..., 422 422 422] [2506 2506 2506 ..., 2559 2559 2559]
399.0 2532.5
segment 486 in image 1
[423 423 423 ..., 469 469 469] [ 0  0  0 ..., 46 46 46]
446.0 23.0
segment 487 in image 1
[423 423 423 ..., 469 469 469] [47 47 47 ..., 93 93 93]
446.0 70.0
segment 488 in image 1
[423 423 423 ..., 469 469 469] [ 94  94  94 ..., 140 140 140]
446.0 117.0
segment 489 in ima

[470 470 470 ..., 516 516 516] [1034 1034 1034 ..., 1080 1080 1080]
493.0 1057.0
segment 563 in image 1
[470 470 470 ..., 516 516 516] [1081 1081 1081 ..., 1127 1127 1127]
493.0 1104.0
segment 564 in image 1
[470 470 470 ..., 516 516 516] [1128 1128 1128 ..., 1174 1174 1174]
493.0 1151.0
segment 565 in image 1
[470 470 470 ..., 516 516 516] [1175 1175 1175 ..., 1221 1221 1221]
493.0 1198.0
segment 566 in image 1
[470 470 470 ..., 516 516 516] [1222 1222 1222 ..., 1268 1268 1268]
493.0 1245.0
segment 567 in image 1
[470 470 470 ..., 516 516 516] [1269 1269 1269 ..., 1315 1315 1315]
493.0 1292.0
segment 568 in image 1
[470 470 470 ..., 516 516 516] [1316 1316 1316 ..., 1362 1362 1362]
493.0 1339.0
segment 569 in image 1
[470 470 470 ..., 516 516 516] [1363 1363 1363 ..., 1409 1409 1409]
493.0 1386.0
segment 570 in image 1
[470 470 470 ..., 516 516 516] [1410 1410 1410 ..., 1456 1456 1456]
493.0 1433.0
segment 571 in image 1
[470 470 470 ..., 516 516 516] [1457 1457 1457 ..., 1503 1503 15

[517 517 517 ..., 563 563 563] [2352 2352 2352 ..., 2401 2401 2401]
540.0 2376.5
segment 645 in image 1
[517 517 517 ..., 563 563 563] [2402 2402 2402 ..., 2452 2452 2452]
540.0 2427.0
segment 646 in image 1
[517 517 517 ..., 563 563 563] [2453 2453 2453 ..., 2505 2505 2505]
540.0 2479.0
segment 647 in image 1
[517 517 517 ..., 563 563 563] [2506 2506 2506 ..., 2559 2559 2559]
540.0 2532.5
segment 648 in image 1
[564 564 564 ..., 610 610 610] [ 0  0  0 ..., 46 46 46]
587.0 23.0
segment 649 in image 1
[564 564 564 ..., 610 610 610] [47 47 47 ..., 93 93 93]
587.0 70.0
segment 650 in image 1
[564 564 564 ..., 610 610 610] [ 94  94  94 ..., 140 140 140]
587.0 117.0
segment 651 in image 1
[564 564 564 ..., 610 610 610] [141 141 141 ..., 187 187 187]
587.0 164.0
segment 652 in image 1
[564 564 564 ..., 610 610 610] [188 188 188 ..., 234 234 234]
587.0 211.0
segment 653 in image 1
[564 564 564 ..., 610 610 610] [235 235 235 ..., 281 281 281]
587.0 258.0
segment 654 in image 1
[564 564 564 ...

[611 611 611 ..., 657 657 657] [1175 1175 1175 ..., 1221 1221 1221]
634.0 1198.0
segment 728 in image 1
[611 611 611 ..., 657 657 657] [1222 1222 1222 ..., 1268 1268 1268]
634.0 1245.0
segment 729 in image 1
[611 611 611 ..., 657 657 657] [1269 1269 1269 ..., 1315 1315 1315]
634.0 1292.0
segment 730 in image 1
[611 611 611 ..., 657 657 657] [1316 1316 1316 ..., 1362 1362 1362]
634.0 1339.0
segment 731 in image 1
[611 611 611 ..., 657 657 657] [1363 1363 1363 ..., 1409 1409 1409]
634.0 1386.0
segment 732 in image 1
[611 611 611 ..., 657 657 657] [1410 1410 1410 ..., 1456 1456 1456]
634.0 1433.0
segment 733 in image 1
[611 611 611 ..., 657 657 657] [1457 1457 1457 ..., 1503 1503 1503]
634.0 1480.0
segment 734 in image 1
[611 611 611 ..., 657 657 657] [1504 1504 1504 ..., 1550 1550 1550]
634.0 1527.0
segment 735 in image 1
[611 611 611 ..., 657 657 657] [1551 1551 1551 ..., 1597 1597 1597]
634.0 1574.0
segment 736 in image 1
[611 611 611 ..., 657 657 657] [1598 1598 1598 ..., 1644 1644 16

[658 658 658 ..., 704 704 704] [2506 2506 2506 ..., 2559 2559 2559]
681.0 2532.5
segment 810 in image 1
[705 705 705 ..., 751 751 751] [ 0  0  0 ..., 46 46 46]
728.0 23.0
segment 811 in image 1
[705 705 705 ..., 751 751 751] [47 47 47 ..., 93 93 93]
728.0 70.0
segment 812 in image 1
[705 705 705 ..., 751 751 751] [ 94  94  94 ..., 140 140 140]
728.0 117.0
segment 813 in image 1
[705 705 705 ..., 751 751 751] [141 141 141 ..., 187 187 187]
728.0 164.0
segment 814 in image 1
[705 705 705 ..., 751 751 751] [188 188 188 ..., 234 234 234]
728.0 211.0
segment 815 in image 1
[705 705 705 ..., 751 751 751] [235 235 235 ..., 281 281 281]
728.0 258.0
segment 816 in image 1
[705 705 705 ..., 751 751 751] [282 282 282 ..., 328 328 328]
728.0 305.0
segment 817 in image 1
[705 705 705 ..., 751 751 751] [329 329 329 ..., 375 375 375]
728.0 352.0
segment 818 in image 1
[705 705 705 ..., 751 751 751] [376 376 376 ..., 422 422 422]
728.0 399.0
segment 819 in image 1
[705 705 705 ..., 751 751 751] [423 4

[752 752 752 ..., 798 798 798] [1269 1269 1269 ..., 1315 1315 1315]
775.0 1292.0
segment 892 in image 1
[752 752 752 ..., 798 798 798] [1316 1316 1316 ..., 1362 1362 1362]
775.0 1339.0
segment 893 in image 1
[752 752 752 ..., 798 798 798] [1363 1363 1363 ..., 1409 1409 1409]
775.0 1386.0
segment 894 in image 1
[752 752 752 ..., 798 798 798] [1410 1410 1410 ..., 1456 1456 1456]
775.0 1433.0
segment 895 in image 1
[752 752 752 ..., 798 798 798] [1457 1457 1457 ..., 1503 1503 1503]
775.0 1480.0
segment 896 in image 1
[752 752 752 ..., 798 798 798] [1504 1504 1504 ..., 1550 1550 1550]
775.0 1527.0
segment 897 in image 1
[752 752 752 ..., 798 798 798] [1551 1551 1551 ..., 1597 1597 1597]
775.0 1574.0
segment 898 in image 1
[752 752 752 ..., 798 798 798] [1598 1598 1598 ..., 1644 1644 1644]
775.0 1621.0
segment 899 in image 1
[752 752 752 ..., 798 798 798] [1645 1645 1645 ..., 1691 1691 1691]
775.0 1668.0
segment 900 in image 1
[752 752 752 ..., 798 798 798] [1692 1692 1692 ..., 1738 1738 17

[846 846 846 ..., 892 892 892] [ 0  0  0 ..., 46 46 46]
869.0 23.0
segment 973 in image 1
[846 846 846 ..., 892 892 892] [47 47 47 ..., 93 93 93]
869.0 70.0
segment 974 in image 1
[846 846 846 ..., 892 892 892] [ 94  94  94 ..., 140 140 140]
869.0 117.0
segment 975 in image 1
[846 846 846 ..., 892 892 892] [141 141 141 ..., 187 187 187]
869.0 164.0
segment 976 in image 1
[846 846 846 ..., 892 892 892] [188 188 188 ..., 234 234 234]
869.0 211.0
segment 977 in image 1
[846 846 846 ..., 892 892 892] [235 235 235 ..., 281 281 281]
869.0 258.0
segment 978 in image 1
[846 846 846 ..., 892 892 892] [282 282 282 ..., 328 328 328]
869.0 305.0
segment 979 in image 1
[846 846 846 ..., 892 892 892] [329 329 329 ..., 375 375 375]
869.0 352.0
segment 980 in image 1
[846 846 846 ..., 892 892 892] [376 376 376 ..., 422 422 422]
869.0 399.0
segment 981 in image 1
[846 846 846 ..., 892 892 892] [423 423 423 ..., 469 469 469]
869.0 446.0
segment 982 in image 1
[846 846 846 ..., 892 892 892] [470 470 470 

[893 893 893 ..., 939 939 939] [1316 1316 1316 ..., 1362 1362 1362]
916.0 1339.0
segment 1055 in image 1
[893 893 893 ..., 939 939 939] [1363 1363 1363 ..., 1409 1409 1409]
916.0 1386.0
segment 1056 in image 1
[893 893 893 ..., 939 939 939] [1410 1410 1410 ..., 1456 1456 1456]
916.0 1433.0
segment 1057 in image 1
[893 893 893 ..., 939 939 939] [1457 1457 1457 ..., 1503 1503 1503]
916.0 1480.0
segment 1058 in image 1
[893 893 893 ..., 939 939 939] [1504 1504 1504 ..., 1550 1550 1550]
916.0 1527.0
segment 1059 in image 1
[893 893 893 ..., 939 939 939] [1551 1551 1551 ..., 1597 1597 1597]
916.0 1574.0
segment 1060 in image 1
[893 893 893 ..., 939 939 939] [1598 1598 1598 ..., 1644 1644 1644]
916.0 1621.0
segment 1061 in image 1
[893 893 893 ..., 939 939 939] [1645 1645 1645 ..., 1691 1691 1691]
916.0 1668.0
segment 1062 in image 1
[893 893 893 ..., 939 939 939] [1692 1692 1692 ..., 1738 1738 1738]
916.0 1715.0
segment 1063 in image 1
[893 893 893 ..., 939 939 939] [1739 1739 1739 ..., 178

[ 987  987  987 ..., 1033 1033 1033] [ 0  0  0 ..., 46 46 46]
1010.0 23.0
segment 1135 in image 1
[ 987  987  987 ..., 1033 1033 1033] [47 47 47 ..., 93 93 93]
1010.0 70.0
segment 1136 in image 1
[ 987  987  987 ..., 1033 1033 1033] [ 94  94  94 ..., 140 140 140]
1010.0 117.0
segment 1137 in image 1
[ 987  987  987 ..., 1033 1033 1033] [141 141 141 ..., 187 187 187]
1010.0 164.0
segment 1138 in image 1
[ 987  987  987 ..., 1033 1033 1033] [188 188 188 ..., 234 234 234]
1010.0 211.0
segment 1139 in image 1
[ 987  987  987 ..., 1033 1033 1033] [235 235 235 ..., 281 281 281]
1010.0 258.0
segment 1140 in image 1
[ 987  987  987 ..., 1033 1033 1033] [282 282 282 ..., 328 328 328]
1010.0 305.0
segment 1141 in image 1
[ 987  987  987 ..., 1033 1033 1033] [329 329 329 ..., 375 375 375]
1010.0 352.0
segment 1142 in image 1
[ 987  987  987 ..., 1033 1033 1033] [376 376 376 ..., 422 422 422]
1010.0 399.0
segment 1143 in image 1
[ 987  987  987 ..., 1033 1033 1033] [423 423 423 ..., 469 469 469]
1

[1034 1034 1034 ..., 1080 1080 1080] [1128 1128 1128 ..., 1174 1174 1174]
1057.0 1151.0
segment 1213 in image 1
[1034 1034 1034 ..., 1080 1080 1080] [1175 1175 1175 ..., 1221 1221 1221]
1057.0 1198.0
segment 1214 in image 1
[1034 1034 1034 ..., 1080 1080 1080] [1222 1222 1222 ..., 1268 1268 1268]
1057.0 1245.0
segment 1215 in image 1
[1034 1034 1034 ..., 1080 1080 1080] [1269 1269 1269 ..., 1315 1315 1315]
1057.0 1292.0
segment 1216 in image 1
[1034 1034 1034 ..., 1080 1080 1080] [1316 1316 1316 ..., 1362 1362 1362]
1057.0 1339.0
segment 1217 in image 1
[1034 1034 1034 ..., 1080 1080 1080] [1363 1363 1363 ..., 1409 1409 1409]
1057.0 1386.0
segment 1218 in image 1
[1034 1034 1034 ..., 1080 1080 1080] [1410 1410 1410 ..., 1456 1456 1456]
1057.0 1433.0
segment 1219 in image 1
[1034 1034 1034 ..., 1080 1080 1080] [1457 1457 1457 ..., 1503 1503 1503]
1057.0 1480.0
segment 1220 in image 1
[1034 1034 1034 ..., 1080 1080 1080] [1504 1504 1504 ..., 1550 1550 1550]
1057.0 1527.0
segment 1221 in 

[1081 1081 1081 ..., 1127 1127 1127] [2162 2162 2162 ..., 2208 2208 2208]
1104.0 2185.0
segment 1289 in image 1
[1081 1081 1081 ..., 1127 1127 1127] [2209 2209 2209 ..., 2255 2255 2255]
1104.0 2232.0
segment 1290 in image 1
[1081 1081 1081 ..., 1127 1127 1127] [2256 2256 2256 ..., 2303 2303 2303]
1104.0 2279.5
segment 1291 in image 1
[1081 1081 1081 ..., 1127 1127 1127] [2304 2304 2304 ..., 2351 2351 2351]
1104.0 2327.5
segment 1292 in image 1
[1081 1081 1081 ..., 1127 1127 1127] [2352 2352 2352 ..., 2401 2401 2401]
1104.0 2376.5
segment 1293 in image 1
[1081 1081 1081 ..., 1127 1127 1127] [2402 2402 2402 ..., 2452 2452 2452]
1104.0 2427.0
segment 1294 in image 1
[1081 1081 1081 ..., 1127 1127 1127] [2453 2453 2453 ..., 2505 2505 2505]
1104.0 2479.0
segment 1295 in image 1
[1081 1081 1081 ..., 1127 1127 1127] [2506 2506 2506 ..., 2559 2559 2559]
1104.0 2532.5
segment 1296 in image 1
[1128 1128 1128 ..., 1174 1174 1174] [ 0  0  0 ..., 46 46 46]
1151.0 23.0
segment 1297 in image 1
[1128 

[1175 1175 1175 ..., 1221 1221 1221] [658 658 658 ..., 704 704 704]
1198.0 681.0
segment 1365 in image 1
[1175 1175 1175 ..., 1221 1221 1221] [705 705 705 ..., 751 751 751]
1198.0 728.0
segment 1366 in image 1
[1175 1175 1175 ..., 1221 1221 1221] [752 752 752 ..., 798 798 798]
1198.0 775.0
segment 1367 in image 1
[1175 1175 1175 ..., 1221 1221 1221] [799 799 799 ..., 845 845 845]
1198.0 822.0
segment 1368 in image 1
[1175 1175 1175 ..., 1221 1221 1221] [846 846 846 ..., 892 892 892]
1198.0 869.0
segment 1369 in image 1
[1175 1175 1175 ..., 1221 1221 1221] [893 893 893 ..., 939 939 939]
1198.0 916.0
segment 1370 in image 1
[1175 1175 1175 ..., 1221 1221 1221] [940 940 940 ..., 986 986 986]
1198.0 963.0
segment 1371 in image 1
[1175 1175 1175 ..., 1221 1221 1221] [ 987  987  987 ..., 1033 1033 1033]
1198.0 1010.0
segment 1372 in image 1
[1175 1175 1175 ..., 1221 1221 1221] [1034 1034 1034 ..., 1080 1080 1080]
1198.0 1057.0
segment 1373 in image 1
[1175 1175 1175 ..., 1221 1221 1221] [108

[1222 1222 1222 ..., 1268 1268 1268] [1692 1692 1692 ..., 1738 1738 1738]
1245.0 1715.0
segment 1441 in image 1
[1222 1222 1222 ..., 1268 1268 1268] [1739 1739 1739 ..., 1785 1785 1785]
1245.0 1762.0
segment 1442 in image 1
[1222 1222 1222 ..., 1268 1268 1268] [1786 1786 1786 ..., 1832 1832 1832]
1245.0 1809.0
segment 1443 in image 1
[1222 1222 1222 ..., 1268 1268 1268] [1833 1833 1833 ..., 1879 1879 1879]
1245.0 1856.0
segment 1444 in image 1
[1222 1222 1222 ..., 1268 1268 1268] [1880 1880 1880 ..., 1926 1926 1926]
1245.0 1903.0
segment 1445 in image 1
[1222 1222 1222 ..., 1268 1268 1268] [1927 1927 1927 ..., 1973 1973 1973]
1245.0 1950.0
segment 1446 in image 1
[1222 1222 1222 ..., 1268 1268 1268] [1974 1974 1974 ..., 2020 2020 2020]
1245.0 1997.0
segment 1447 in image 1
[1222 1222 1222 ..., 1268 1268 1268] [2021 2021 2021 ..., 2067 2067 2067]
1245.0 2044.0
segment 1448 in image 1
[1222 1222 1222 ..., 1268 1268 1268] [2068 2068 2068 ..., 2114 2114 2114]
1245.0 2091.0
segment 1449 in 

[1316 1316 1316 ..., 1362 1362 1362] [188 188 188 ..., 234 234 234]
1339.0 211.0
segment 1517 in image 1
[1316 1316 1316 ..., 1362 1362 1362] [235 235 235 ..., 281 281 281]
1339.0 258.0
segment 1518 in image 1
[1316 1316 1316 ..., 1362 1362 1362] [282 282 282 ..., 328 328 328]
1339.0 305.0
segment 1519 in image 1
[1316 1316 1316 ..., 1362 1362 1362] [329 329 329 ..., 375 375 375]
1339.0 352.0
segment 1520 in image 1
[1316 1316 1316 ..., 1362 1362 1362] [376 376 376 ..., 422 422 422]
1339.0 399.0
segment 1521 in image 1
[1316 1316 1316 ..., 1362 1362 1362] [423 423 423 ..., 469 469 469]
1339.0 446.0
segment 1522 in image 1
[1316 1316 1316 ..., 1362 1362 1362] [470 470 470 ..., 516 516 516]
1339.0 493.0
segment 1523 in image 1
[1316 1316 1316 ..., 1362 1362 1362] [517 517 517 ..., 563 563 563]
1339.0 540.0
segment 1524 in image 1
[1316 1316 1316 ..., 1362 1362 1362] [564 564 564 ..., 610 610 610]
1339.0 587.0
segment 1525 in image 1
[1316 1316 1316 ..., 1362 1362 1362] [611 611 611 ..., 

[1363 1363 1363 ..., 1409 1409 1409] [1269 1269 1269 ..., 1315 1315 1315]
1386.0 1292.0
segment 1594 in image 1
[1363 1363 1363 ..., 1409 1409 1409] [1316 1316 1316 ..., 1362 1362 1362]
1386.0 1339.0
segment 1595 in image 1
[1363 1363 1363 ..., 1409 1409 1409] [1363 1363 1363 ..., 1409 1409 1409]
1386.0 1386.0
segment 1596 in image 1
[1363 1363 1363 ..., 1409 1409 1409] [1410 1410 1410 ..., 1456 1456 1456]
1386.0 1433.0
segment 1597 in image 1
[1363 1363 1363 ..., 1409 1409 1409] [1457 1457 1457 ..., 1503 1503 1503]
1386.0 1480.0
segment 1598 in image 1
[1363 1363 1363 ..., 1409 1409 1409] [1504 1504 1504 ..., 1550 1550 1550]
1386.0 1527.0
segment 1599 in image 1
[1363 1363 1363 ..., 1409 1409 1409] [1551 1551 1551 ..., 1597 1597 1597]
1386.0 1574.0
segment 1600 in image 1
[1363 1363 1363 ..., 1409 1409 1409] [1598 1598 1598 ..., 1644 1644 1644]
1386.0 1621.0
segment 1601 in image 1
[1363 1363 1363 ..., 1409 1409 1409] [1645 1645 1645 ..., 1691 1691 1691]
1386.0 1668.0
segment 1602 in 

1433.0 2232.0
segment 1668 in image 1
[1410 1410 1410 ..., 1456 1456 1456] [2256 2256 2256 ..., 2303 2303 2303]
1433.0 2279.5
segment 1669 in image 1
[1410 1410 1410 ..., 1456 1456 1456] [2304 2304 2304 ..., 2351 2351 2351]
1433.0 2327.5
segment 1670 in image 1
[1410 1410 1410 ..., 1456 1456 1456] [2352 2352 2352 ..., 2401 2401 2401]
1433.0 2376.5
segment 1671 in image 1
[1410 1410 1410 ..., 1456 1456 1456] [2402 2402 2402 ..., 2452 2452 2452]
1433.0 2427.0
segment 1672 in image 1
[1410 1410 1410 ..., 1456 1456 1456] [2453 2453 2453 ..., 2505 2505 2505]
1433.0 2479.0
segment 1673 in image 1
[1410 1410 1410 ..., 1456 1456 1456] [2506 2506 2506 ..., 2559 2559 2559]
1433.0 2532.5
segment 1674 in image 1
[1457 1457 1457 ..., 1503 1503 1503] [ 0  0  0 ..., 46 46 46]
1480.0 23.0
segment 1675 in image 1
[1457 1457 1457 ..., 1503 1503 1503] [47 47 47 ..., 93 93 93]
1480.0 70.0
segment 1676 in image 1
[1457 1457 1457 ..., 1503 1503 1503] [ 94  94  94 ..., 140 140 140]
1480.0 117.0
segment 1677 

segment 1744 in image 1
[1504 1504 1504 ..., 1550 1550 1550] [752 752 752 ..., 798 798 798]
1527.0 775.0
segment 1745 in image 1
[1504 1504 1504 ..., 1550 1550 1550] [799 799 799 ..., 845 845 845]
1527.0 822.0
segment 1746 in image 1
[1504 1504 1504 ..., 1550 1550 1550] [846 846 846 ..., 892 892 892]
1527.0 869.0
segment 1747 in image 1
[1504 1504 1504 ..., 1550 1550 1550] [893 893 893 ..., 939 939 939]
1527.0 916.0
segment 1748 in image 1
[1504 1504 1504 ..., 1550 1550 1550] [940 940 940 ..., 986 986 986]
1527.0 963.0
segment 1749 in image 1
[1504 1504 1504 ..., 1550 1550 1550] [ 987  987  987 ..., 1033 1033 1033]
1527.0 1010.0
segment 1750 in image 1
[1504 1504 1504 ..., 1550 1550 1550] [1034 1034 1034 ..., 1080 1080 1080]
1527.0 1057.0
segment 1751 in image 1
[1504 1504 1504 ..., 1550 1550 1550] [1081 1081 1081 ..., 1127 1127 1127]
1527.0 1104.0
segment 1752 in image 1
[1504 1504 1504 ..., 1550 1550 1550] [1128 1128 1128 ..., 1174 1174 1174]
1527.0 1151.0
segment 1753 in image 1
[15

[1551 1551 1551 ..., 1597 1597 1597] [1739 1739 1739 ..., 1785 1785 1785]
1574.0 1762.0
segment 1820 in image 1
[1551 1551 1551 ..., 1597 1597 1597] [1786 1786 1786 ..., 1832 1832 1832]
1574.0 1809.0
segment 1821 in image 1
[1551 1551 1551 ..., 1597 1597 1597] [1833 1833 1833 ..., 1879 1879 1879]
1574.0 1856.0
segment 1822 in image 1
[1551 1551 1551 ..., 1597 1597 1597] [1880 1880 1880 ..., 1926 1926 1926]
1574.0 1903.0
segment 1823 in image 1
[1551 1551 1551 ..., 1597 1597 1597] [1927 1927 1927 ..., 1973 1973 1973]
1574.0 1950.0
segment 1824 in image 1
[1551 1551 1551 ..., 1597 1597 1597] [1974 1974 1974 ..., 2020 2020 2020]
1574.0 1997.0
segment 1825 in image 1
[1551 1551 1551 ..., 1597 1597 1597] [2021 2021 2021 ..., 2067 2067 2067]
1574.0 2044.0
segment 1826 in image 1
[1551 1551 1551 ..., 1597 1597 1597] [2068 2068 2068 ..., 2114 2114 2114]
1574.0 2091.0
segment 1827 in image 1
[1551 1551 1551 ..., 1597 1597 1597] [2115 2115 2115 ..., 2161 2161 2161]
1574.0 2138.0
segment 1828 in 

[1645 1645 1645 ..., 1691 1691 1691] [188 188 188 ..., 234 234 234]
1668.0 211.0
segment 1895 in image 1
[1645 1645 1645 ..., 1691 1691 1691] [235 235 235 ..., 281 281 281]
1668.0 258.0
segment 1896 in image 1
[1645 1645 1645 ..., 1691 1691 1691] [282 282 282 ..., 328 328 328]
1668.0 305.0
segment 1897 in image 1
[1645 1645 1645 ..., 1691 1691 1691] [329 329 329 ..., 375 375 375]
1668.0 352.0
segment 1898 in image 1
[1645 1645 1645 ..., 1691 1691 1691] [376 376 376 ..., 422 422 422]
1668.0 399.0
segment 1899 in image 1
[1645 1645 1645 ..., 1691 1691 1691] [423 423 423 ..., 469 469 469]
1668.0 446.0
segment 1900 in image 1
[1645 1645 1645 ..., 1691 1691 1691] [470 470 470 ..., 516 516 516]
1668.0 493.0
segment 1901 in image 1
[1645 1645 1645 ..., 1691 1691 1691] [517 517 517 ..., 563 563 563]
1668.0 540.0
segment 1902 in image 1
[1645 1645 1645 ..., 1691 1691 1691] [564 564 564 ..., 610 610 610]
1668.0 587.0
segment 1903 in image 1
[1645 1645 1645 ..., 1691 1691 1691] [611 611 611 ..., 

[1692 1692 1692 ..., 1738 1738 1738] [1222 1222 1222 ..., 1268 1268 1268]
1715.0 1245.0
segment 1971 in image 1
[1692 1692 1692 ..., 1738 1738 1738] [1269 1269 1269 ..., 1315 1315 1315]
1715.0 1292.0
segment 1972 in image 1
[1692 1692 1692 ..., 1738 1738 1738] [1316 1316 1316 ..., 1362 1362 1362]
1715.0 1339.0
segment 1973 in image 1
[1692 1692 1692 ..., 1738 1738 1738] [1363 1363 1363 ..., 1409 1409 1409]
1715.0 1386.0
segment 1974 in image 1
[1692 1692 1692 ..., 1738 1738 1738] [1410 1410 1410 ..., 1456 1456 1456]
1715.0 1433.0
segment 1975 in image 1
[1692 1692 1692 ..., 1738 1738 1738] [1457 1457 1457 ..., 1503 1503 1503]
1715.0 1480.0
segment 1976 in image 1
[1692 1692 1692 ..., 1738 1738 1738] [1504 1504 1504 ..., 1550 1550 1550]
1715.0 1527.0
segment 1977 in image 1
[1692 1692 1692 ..., 1738 1738 1738] [1551 1551 1551 ..., 1597 1597 1597]
1715.0 1574.0
segment 1978 in image 1
[1692 1692 1692 ..., 1738 1738 1738] [1598 1598 1598 ..., 1644 1644 1644]
1715.0 1621.0
segment 1979 in 

[1739 1739 1739 ..., 1785 1785 1785] [2209 2209 2209 ..., 2255 2255 2255]
1762.0 2232.0
segment 2046 in image 1
[1739 1739 1739 ..., 1785 1785 1785] [2256 2256 2256 ..., 2303 2303 2303]
1762.0 2279.5
segment 2047 in image 1
[1739 1739 1739 ..., 1785 1785 1785] [2304 2304 2304 ..., 2351 2351 2351]
1762.0 2327.5
segment 2048 in image 1
[1739 1739 1739 ..., 1785 1785 1785] [2352 2352 2352 ..., 2401 2401 2401]
1762.0 2376.5
segment 2049 in image 1
[1739 1739 1739 ..., 1785 1785 1785] [2402 2402 2402 ..., 2452 2452 2452]
1762.0 2427.0
segment 2050 in image 1
[1739 1739 1739 ..., 1785 1785 1785] [2453 2453 2453 ..., 2505 2505 2505]
1762.0 2479.0
segment 2051 in image 1
[1739 1739 1739 ..., 1785 1785 1785] [2506 2506 2506 ..., 2559 2559 2559]
1762.0 2532.5
segment 2052 in image 1
[1786 1786 1786 ..., 1832 1832 1832] [ 0  0  0 ..., 46 46 46]
1809.0 23.0
segment 2053 in image 1
[1786 1786 1786 ..., 1832 1832 1832] [47 47 47 ..., 93 93 93]
1809.0 70.0
segment 2054 in image 1
[1786 1786 1786 ...,

[1833 1833 1833 ..., 1879 1879 1879] [705 705 705 ..., 751 751 751]
1856.0 728.0
segment 2122 in image 1
[1833 1833 1833 ..., 1879 1879 1879] [752 752 752 ..., 798 798 798]
1856.0 775.0
segment 2123 in image 1
[1833 1833 1833 ..., 1879 1879 1879] [799 799 799 ..., 845 845 845]
1856.0 822.0
segment 2124 in image 1
[1833 1833 1833 ..., 1879 1879 1879] [846 846 846 ..., 892 892 892]
1856.0 869.0
segment 2125 in image 1
[1833 1833 1833 ..., 1879 1879 1879] [893 893 893 ..., 939 939 939]
1856.0 916.0
segment 2126 in image 1
[1833 1833 1833 ..., 1879 1879 1879] [940 940 940 ..., 986 986 986]
1856.0 963.0
segment 2127 in image 1
[1833 1833 1833 ..., 1879 1879 1879] [ 987  987  987 ..., 1033 1033 1033]
1856.0 1010.0
segment 2128 in image 1
[1833 1833 1833 ..., 1879 1879 1879] [1034 1034 1034 ..., 1080 1080 1080]
1856.0 1057.0
segment 2129 in image 1
[1833 1833 1833 ..., 1879 1879 1879] [1081 1081 1081 ..., 1127 1127 1127]
1856.0 1104.0
segment 2130 in image 1
[1833 1833 1833 ..., 1879 1879 187

[1880 1880 1880 ..., 1926 1926 1926] [1692 1692 1692 ..., 1738 1738 1738]
1903.0 1715.0
segment 2197 in image 1
[1880 1880 1880 ..., 1926 1926 1926] [1739 1739 1739 ..., 1785 1785 1785]
1903.0 1762.0
segment 2198 in image 1
[1880 1880 1880 ..., 1926 1926 1926] [1786 1786 1786 ..., 1832 1832 1832]
1903.0 1809.0
segment 2199 in image 1
[1880 1880 1880 ..., 1926 1926 1926] [1833 1833 1833 ..., 1879 1879 1879]
1903.0 1856.0
segment 2200 in image 1
[1880 1880 1880 ..., 1926 1926 1926] [1880 1880 1880 ..., 1926 1926 1926]
1903.0 1903.0
segment 2201 in image 1
[1880 1880 1880 ..., 1926 1926 1926] [1927 1927 1927 ..., 1973 1973 1973]
1903.0 1950.0
segment 2202 in image 1
[1880 1880 1880 ..., 1926 1926 1926] [1974 1974 1974 ..., 2020 2020 2020]
1903.0 1997.0
segment 2203 in image 1
[1880 1880 1880 ..., 1926 1926 1926] [2021 2021 2021 ..., 2067 2067 2067]
1903.0 2044.0
segment 2204 in image 1
[1880 1880 1880 ..., 1926 1926 1926] [2068 2068 2068 ..., 2114 2114 2114]
1903.0 2091.0
segment 2205 in 

[1974 1974 1974 ..., 2020 2020 2020] [188 188 188 ..., 234 234 234]
1997.0 211.0
segment 2273 in image 1
[1974 1974 1974 ..., 2020 2020 2020] [235 235 235 ..., 281 281 281]
1997.0 258.0
segment 2274 in image 1
[1974 1974 1974 ..., 2020 2020 2020] [282 282 282 ..., 328 328 328]
1997.0 305.0
segment 2275 in image 1
[1974 1974 1974 ..., 2020 2020 2020] [329 329 329 ..., 375 375 375]
1997.0 352.0
segment 2276 in image 1
[1974 1974 1974 ..., 2020 2020 2020] [376 376 376 ..., 422 422 422]
1997.0 399.0
segment 2277 in image 1
[1974 1974 1974 ..., 2020 2020 2020] [423 423 423 ..., 469 469 469]
1997.0 446.0
segment 2278 in image 1
[1974 1974 1974 ..., 2020 2020 2020] [470 470 470 ..., 516 516 516]
1997.0 493.0
segment 2279 in image 1
[1974 1974 1974 ..., 2020 2020 2020] [517 517 517 ..., 563 563 563]
1997.0 540.0
segment 2280 in image 1
[1974 1974 1974 ..., 2020 2020 2020] [564 564 564 ..., 610 610 610]
1997.0 587.0
segment 2281 in image 1
[1974 1974 1974 ..., 2020 2020 2020] [611 611 611 ..., 

[2021 2021 2021 ..., 2067 2067 2067] [1222 1222 1222 ..., 1268 1268 1268]
2044.0 1245.0
segment 2349 in image 1
[2021 2021 2021 ..., 2067 2067 2067] [1269 1269 1269 ..., 1315 1315 1315]
2044.0 1292.0
segment 2350 in image 1
[2021 2021 2021 ..., 2067 2067 2067] [1316 1316 1316 ..., 1362 1362 1362]
2044.0 1339.0
segment 2351 in image 1
[2021 2021 2021 ..., 2067 2067 2067] [1363 1363 1363 ..., 1409 1409 1409]
2044.0 1386.0
segment 2352 in image 1
[2021 2021 2021 ..., 2067 2067 2067] [1410 1410 1410 ..., 1456 1456 1456]
2044.0 1433.0
segment 2353 in image 1
[2021 2021 2021 ..., 2067 2067 2067] [1457 1457 1457 ..., 1503 1503 1503]
2044.0 1480.0
segment 2354 in image 1
[2021 2021 2021 ..., 2067 2067 2067] [1504 1504 1504 ..., 1550 1550 1550]
2044.0 1527.0
segment 2355 in image 1
[2021 2021 2021 ..., 2067 2067 2067] [1551 1551 1551 ..., 1597 1597 1597]
2044.0 1574.0
segment 2356 in image 1
[2021 2021 2021 ..., 2067 2067 2067] [1598 1598 1598 ..., 1644 1644 1644]
2044.0 1621.0
segment 2357 in 

[2068 2068 2068 ..., 2114 2114 2114] [2209 2209 2209 ..., 2255 2255 2255]
2091.0 2232.0
segment 2424 in image 1
[2068 2068 2068 ..., 2114 2114 2114] [2256 2256 2256 ..., 2303 2303 2303]
2091.0 2279.5
segment 2425 in image 1
[2068 2068 2068 ..., 2114 2114 2114] [2304 2304 2304 ..., 2351 2351 2351]
2091.0 2327.5
segment 2426 in image 1
[2068 2068 2068 ..., 2114 2114 2114] [2352 2352 2352 ..., 2401 2401 2401]
2091.0 2376.5
segment 2427 in image 1
[2068 2068 2068 ..., 2114 2114 2114] [2402 2402 2402 ..., 2452 2452 2452]
2091.0 2427.0
segment 2428 in image 1
[2068 2068 2068 ..., 2114 2114 2114] [2453 2453 2453 ..., 2505 2505 2505]
2091.0 2479.0
segment 2429 in image 1
[2068 2068 2068 ..., 2114 2114 2114] [2506 2506 2506 ..., 2559 2559 2559]
2091.0 2532.5
segment 2430 in image 1
[2115 2115 2115 ..., 2161 2161 2161] [ 0  0  0 ..., 46 46 46]
2138.0 23.0
segment 2431 in image 1
[2115 2115 2115 ..., 2161 2161 2161] [47 47 47 ..., 93 93 93]
2138.0 70.0
segment 2432 in image 1
[2115 2115 2115 ...,

[2162 2162 2162 ..., 2208 2208 2208] [752 752 752 ..., 798 798 798]
2185.0 775.0
segment 2501 in image 1
[2162 2162 2162 ..., 2208 2208 2208] [799 799 799 ..., 845 845 845]
2185.0 822.0
segment 2502 in image 1
[2162 2162 2162 ..., 2208 2208 2208] [846 846 846 ..., 892 892 892]
2185.0 869.0
segment 2503 in image 1
[2162 2162 2162 ..., 2208 2208 2208] [893 893 893 ..., 939 939 939]
2185.0 916.0
segment 2504 in image 1
[2162 2162 2162 ..., 2208 2208 2208] [940 940 940 ..., 986 986 986]
2185.0 963.0
segment 2505 in image 1
[2162 2162 2162 ..., 2208 2208 2208] [ 987  987  987 ..., 1033 1033 1033]
2185.0 1010.0
segment 2506 in image 1
[2162 2162 2162 ..., 2208 2208 2208] [1034 1034 1034 ..., 1080 1080 1080]
2185.0 1057.0
segment 2507 in image 1
[2162 2162 2162 ..., 2208 2208 2208] [1081 1081 1081 ..., 1127 1127 1127]
2185.0 1104.0
segment 2508 in image 1
[2162 2162 2162 ..., 2208 2208 2208] [1128 1128 1128 ..., 1174 1174 1174]
2185.0 1151.0
segment 2509 in image 1
[2162 2162 2162 ..., 2208 2

[2209 2209 2209 ..., 2255 2255 2255] [1786 1786 1786 ..., 1832 1832 1832]
2232.0 1809.0
segment 2577 in image 1
[2209 2209 2209 ..., 2255 2255 2255] [1833 1833 1833 ..., 1879 1879 1879]
2232.0 1856.0
segment 2578 in image 1
[2209 2209 2209 ..., 2255 2255 2255] [1880 1880 1880 ..., 1926 1926 1926]
2232.0 1903.0
segment 2579 in image 1
[2209 2209 2209 ..., 2255 2255 2255] [1927 1927 1927 ..., 1973 1973 1973]
2232.0 1950.0
segment 2580 in image 1
[2209 2209 2209 ..., 2255 2255 2255] [1974 1974 1974 ..., 2020 2020 2020]
2232.0 1997.0
segment 2581 in image 1
[2209 2209 2209 ..., 2255 2255 2255] [2021 2021 2021 ..., 2067 2067 2067]
2232.0 2044.0
segment 2582 in image 1
[2209 2209 2209 ..., 2255 2255 2255] [2068 2068 2068 ..., 2114 2114 2114]
2232.0 2091.0
segment 2583 in image 1
[2209 2209 2209 ..., 2255 2255 2255] [2115 2115 2115 ..., 2161 2161 2161]
2232.0 2138.0
segment 2584 in image 1
[2209 2209 2209 ..., 2255 2255 2255] [2162 2162 2162 ..., 2208 2208 2208]
2232.0 2185.0
segment 2585 in 

[2304 2304 2304 ..., 2351 2351 2351] [329 329 329 ..., 375 375 375]
2327.5 352.0
segment 2654 in image 1
[2304 2304 2304 ..., 2351 2351 2351] [376 376 376 ..., 422 422 422]
2327.5 399.0
segment 2655 in image 1
[2304 2304 2304 ..., 2351 2351 2351] [423 423 423 ..., 469 469 469]
2327.5 446.0
segment 2656 in image 1
[2304 2304 2304 ..., 2351 2351 2351] [470 470 470 ..., 516 516 516]
2327.5 493.0
segment 2657 in image 1
[2304 2304 2304 ..., 2351 2351 2351] [517 517 517 ..., 563 563 563]
2327.5 540.0
segment 2658 in image 1
[2304 2304 2304 ..., 2351 2351 2351] [564 564 564 ..., 610 610 610]
2327.5 587.0
segment 2659 in image 1
[2304 2304 2304 ..., 2351 2351 2351] [611 611 611 ..., 657 657 657]
2327.5 634.0
segment 2660 in image 1
[2304 2304 2304 ..., 2351 2351 2351] [658 658 658 ..., 704 704 704]
2327.5 681.0
segment 2661 in image 1
[2304 2304 2304 ..., 2351 2351 2351] [705 705 705 ..., 751 751 751]
2327.5 728.0
segment 2662 in image 1
[2304 2304 2304 ..., 2351 2351 2351] [752 752 752 ..., 

[2352 2352 2352 ..., 2401 2401 2401] [1410 1410 1410 ..., 1456 1456 1456]
2376.5 1433.0
segment 2731 in image 1
[2352 2352 2352 ..., 2401 2401 2401] [1457 1457 1457 ..., 1503 1503 1503]
2376.5 1480.0
segment 2732 in image 1
[2352 2352 2352 ..., 2401 2401 2401] [1504 1504 1504 ..., 1550 1550 1550]
2376.5 1527.0
segment 2733 in image 1
[2352 2352 2352 ..., 2401 2401 2401] [1551 1551 1551 ..., 1597 1597 1597]
2376.5 1574.0
segment 2734 in image 1
[2352 2352 2352 ..., 2401 2401 2401] [1598 1598 1598 ..., 1644 1644 1644]
2376.5 1621.0
segment 2735 in image 1
[2352 2352 2352 ..., 2401 2401 2401] [1645 1645 1645 ..., 1691 1691 1691]
2376.5 1668.0
segment 2736 in image 1
[2352 2352 2352 ..., 2401 2401 2401] [1692 1692 1692 ..., 1738 1738 1738]
2376.5 1715.0
segment 2737 in image 1
[2352 2352 2352 ..., 2401 2401 2401] [1739 1739 1739 ..., 1785 1785 1785]
2376.5 1762.0
segment 2738 in image 1
[2352 2352 2352 ..., 2401 2401 2401] [1786 1786 1786 ..., 1832 1832 1832]
2376.5 1809.0
segment 2739 in 

[2402 2402 2402 ..., 2452 2452 2452] [2453 2453 2453 ..., 2505 2505 2505]
2427.0 2479.0
segment 2807 in image 1
[2402 2402 2402 ..., 2452 2452 2452] [2506 2506 2506 ..., 2559 2559 2559]
2427.0 2532.5
segment 2808 in image 1
[2453 2453 2453 ..., 2505 2505 2505] [ 0  0  0 ..., 46 46 46]
2479.0 23.0
segment 2809 in image 1
[2453 2453 2453 ..., 2505 2505 2505] [47 47 47 ..., 93 93 93]
2479.0 70.0
segment 2810 in image 1
[2453 2453 2453 ..., 2505 2505 2505] [ 94  94  94 ..., 140 140 140]
2479.0 117.0
segment 2811 in image 1
[2453 2453 2453 ..., 2505 2505 2505] [141 141 141 ..., 187 187 187]
2479.0 164.0
segment 2812 in image 1
[2453 2453 2453 ..., 2505 2505 2505] [188 188 188 ..., 234 234 234]
2479.0 211.0
segment 2813 in image 1
[2453 2453 2453 ..., 2505 2505 2505] [235 235 235 ..., 281 281 281]
2479.0 258.0
segment 2814 in image 1
[2453 2453 2453 ..., 2505 2505 2505] [282 282 282 ..., 328 328 328]
2479.0 305.0
segment 2815 in image 1
[2453 2453 2453 ..., 2505 2505 2505] [329 329 329 ..., 

[2506 2506 2506 ..., 2559 2559 2559] [940 940 940 ..., 986 986 986]
2532.5 963.0
segment 2883 in image 1
[2506 2506 2506 ..., 2559 2559 2559] [ 987  987  987 ..., 1033 1033 1033]
2532.5 1010.0
segment 2884 in image 1
[2506 2506 2506 ..., 2559 2559 2559] [1034 1034 1034 ..., 1080 1080 1080]
2532.5 1057.0
segment 2885 in image 1
[2506 2506 2506 ..., 2559 2559 2559] [1081 1081 1081 ..., 1127 1127 1127]
2532.5 1104.0
segment 2886 in image 1
[2506 2506 2506 ..., 2559 2559 2559] [1128 1128 1128 ..., 1174 1174 1174]
2532.5 1151.0
segment 2887 in image 1
[2506 2506 2506 ..., 2559 2559 2559] [1175 1175 1175 ..., 1221 1221 1221]
2532.5 1198.0
segment 2888 in image 1
[2506 2506 2506 ..., 2559 2559 2559] [1222 1222 1222 ..., 1268 1268 1268]
2532.5 1245.0
segment 2889 in image 1
[2506 2506 2506 ..., 2559 2559 2559] [1269 1269 1269 ..., 1315 1315 1315]
2532.5 1292.0
segment 2890 in image 1
[2506 2506 2506 ..., 2559 2559 2559] [1316 1316 1316 ..., 1362 1362 1362]
2532.5 1339.0
segment 2891 in image 1